CREATE TABLE "PDPUR102" ("CHGDATE" CHAR(30) NOT NULL, "CHGCD" CHAR(1) NOT NULL, "VSRNO" CHAR(8) NOT NULL, "INSIDE" CHAR(1) NOT NULL, 
"KBCD" CHAR(1) NOT NULL, "VANCD" CHAR(1) NOT NULL, "JSCD" CHAR(1) NOT NULL, "XSTOP" CHAR(1) NOT NULL, "STSCD" CHAR(1) NOT NULL, "DOWNDATE" CHAR(30) NOT NULL , 
PRIMARY KEY ("CHGDATE")) ;
;
insert into "PBCOMMON".pbcattbl (pbt_tnam, pbt_ownr, pbd_fhgt, pbd_fwgt, pbd_fitl, pbd_funl, pbd_fchr, pbd_fptc, pbd_ffce, pbh_fhgt, pbh_fwgt, pbh_fitl, pbh_funl, pbh_fchr, pbh_fptc, pbh_ffce, pbl_fhgt, pbl_fwgt, pbl_fitl, pbl_funl, pbl_fchr, pbl_fptc, pbl_ffce, pbt_cmnt) values ('PDPUR102', 'PBIPIS', -10, 400, 'N', 'N', 0, 34, '굴림체          ', -10, 400, 'N', 'N', 0, 34, '굴림체          ', -10, 400 , 'N', 'N', 0, 34, '굴림체          ', 'Supplier/Customer Master') ;insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'CHGDATE', '변경일', 23 , '변경일', 25, 25 , 0 , 0 , 0 , 'N', '변경일' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'CHGCD', '변경코드', 23 , '변경코드', 25, 25 , 0 , 0 , 0 , 'N', '변경코드' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'VSRNO', '업체전산번호', 23 , '업체전산번호', 25, 25 , 0 , 0 , 0 , 'N', '업체전산번호' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'INSIDE', '사내업체구분', 23 , '사내업체구분', 25, 25 , 0 , 0 , 0 , 'N', '사내업체구분' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'KBCD', '간판대상업체', 23 , '간판대상업체', 25, 25 , 0 , 0 , 0 , 'N', '간판대상업체' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'VANCD', 'VAN대상업체', 23 , 'VAN대상업체', 25, 25 , 0 , 0 , 0 , 'N', 'VAN대상업체' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'JSCD', '마감주기', 23 , '마감주기', 25, 25 , 0 , 0 , 0 , 'N', '마감주기' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'XSTOP', '업체중단', 23 , '업체중단', 25, 25 , 0 , 0 , 0 , 'N', '업체중단' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'STSCD', '상태코드', 23 , '상태코드', 25, 25 , 0 , 0 , 0 , 'N', '상태코드' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('PDPUR102', 'PBIPIS', 'DOWNDATE', 'DOWN일자', 23 , 'DOWN일자', 25, 25 , 0 , 0 , 0 , 'N', 'DOWN일자' ) ;

