// CREATE TABLE QTEMP.EPLTEMP ( TMODL CHAR(15) NOT NULL, TSERL CHAR(60) NOT NULL, TLEVEL CHAR(2) NOT NULL, TPITN CHAR(15) NOT NULL,
//				 TCITN CHAR(15) NOT NULL, TQTYM NUMERIC(8,3) NOT NULL, TQTY1 NUMERIC(8,3) NOT NULL,
//				 TEDTM CHAR(8) NOT NULL, TEDTE CHAR(8) NOT NULL, TECNNUMBER CHAR(15) NOT NULL,TDRAWING CHAR(16) NOT NULL ) 
//;