--  Generate SQL
--  Version:                    V5R3M0 040528
--  Generated on:               08/08/12 10:51:31
--  Relational Database:        I520
--  Standards Option:           DB2 UDB iSeries

DROP TABLE PBWIP.WIP015;

CREATE TABLE PBWIP.WIP015 (
  TCMCD     CHAR(2)       CCSID 833 NOT NULL ,
  TYEAR     CHAR(4)       CCSID 833 NOT NULL ,
  TMONTH    CHAR(2)       CCSID 833 NOT NULL ,
  TPLNT     CHAR(1)       CCSID 833 NOT NULL ,
  TDVSN     CHAR(1)       CCSID 833 NOT NULL ,
  TMODL     CHAR(15)      CCSID 833 NOT NULL ,
  TLEVEL    NUMERIC(2,0)  NOT NULL ,
  TPITN     CHAR(15)      CCSID 933 NOT NULL ,
  TCITN     CHAR(15)      CCSID 933 NOT NULL ,
  TQTYM     NUMERIC(8,3)  NOT NULL ,
  TQTY1     NUMERIC(8,3)  NOT NULL ,
  TWKCT     CHAR(4)       CCSID 833 NOT NULL ,
  TEDTM     CHAR(8)       CCSID 833 NOT NULL ,
  TEDTE     CHAR(8)       CCSID 833 NOT NULL ,
  TOPTION   CHAR(15)      CCSID 933 NOT NULL ,
  TOPCD     CHAR(1)       CCSID 833 NOT NULL ,
  TEXPLANT  CHAR(1)       CCSID 833 NOT NULL ,
  TEXDV     CHAR(1)       CCSID 833 NOT NULL ,
  TOSCD     CHAR(1)       CCSID 833 NOT NULL ,
  TCHGCHK   CHAR(1)       CCSID 833 NOT NULL ,
  TSERL     VARCHAR(600)  CCSID 833 NOT NULL ,
  PRIMARY KEY( TCMCD,TYEAR,TMONTH,TPLNT,TDVSN,TMODL,TPITN,TCITN,TSERL ) ) ;