--  Generate SQL
--  Version:                    V5R3M0 040528
--  Generated on:               08/08/14 12:05:29
--  Relational Database:        I520
--  Standards Option:           DB2 UDB iSeries
--  Desc : 재공금액 작업에 따른 차이금액 산정

DROP TABLE PBWIP.WIP018;
CREATE TABLE PBWIP.WIP018 (
  WBCMCD CHAR(2) CCSID 833 NOT NULL ,
  WBYYMMDD CHAR(8) CCSID 833 NOT NULL ,  -- 작업날짜
  WBYEAR CHAR(4) CCSID 933 NOT NULL ,    -- 재공마감년도
	WBMONTH CHAR(2) CCSID 833 NOT NULL ,   -- 재공마감월
  WBPLANT CHAR(1) CCSID 833 NOT NULL ,
  WBDVSN CHAR(1) CCSID 833 NOT NULL ,
  WBIOCD CHAR(1) CCSID 833 NOT NULL ,
  WBBGAT1 DECIMAL(15, 0) NOT NULL ,
  WBINAT1 DECIMAL(15, 0) NOT NULL ,
  WBINAT2 DECIMAL(15, 0) NOT NULL ,
  WBINAT3 DECIMAL(15, 0) NOT NULL ,
  WBINAT4 DECIMAL(15, 0) NOT NULL ,
  WBUSAT1 DECIMAL(15, 0) NOT NULL ,
  WBUSAT2 DECIMAL(15, 0) NOT NULL ,
  WBUSAT3 DECIMAL(15, 0) NOT NULL ,
  WBUSAT4 DECIMAL(15, 0) NOT NULL ,
  WBUSAT5 DECIMAL(15, 0) NOT NULL ,
  WBUSAT6 DECIMAL(15, 0) NOT NULL ,
  WBUSAT7 DECIMAL(15, 0) NOT NULL ,
  WBUSAT8 DECIMAL(15, 0) NOT NULL ,
  WBUSAT9 DECIMAL(15, 0) NOT NULL ,
  WBUSATA DECIMAL(15, 0) NOT NULL ,
  WBOHAT1 DECIMAL(15, 0) NOT NULL ,  -- 현재공금액
  WBOHATA DECIMAL(15, 0) NOT NULL ,  -- 익월기초금액
  WBINPTDT CHAR(8) CCSID 933 NOT NULL ,
  PRIMARY KEY( WBCMCD , WBYYMMDD , WBYEAR, WBMONTH, WBPLANT , WBDVSN , WBIOCD ) ) ;