--  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	08/08/14 12:11:11 
--  Relational Database:       	I520 
--  Standards Option:          	DB2 UDB iSeries 
DROP TABLE PBWIP.WIP009;
CREATE TABLE PBWIP.WIP009 ( 
	WFYEAR CHAR(4) CCSID 933 NOT NULL , 
	WFMONTH CHAR(2) CCSID 833 NOT NULL , 
	WFCMCD CHAR(2) CCSID 833 NOT NULL , 
	WFPLANT CHAR(1) CCSID 833 NOT NULL , 
	WFDVSN CHAR(1) CCSID 833 NOT NULL , 
	WFIOCD CHAR(1) CCSID 833 NOT NULL , 
	WFVENDOR VARCHAR(5) CCSID 933 NOT NULL , 
	WFITNO CHAR(15) CCSID 933 NOT NULL , 
	WFUNIT CHAR(2) CCSID 833 NOT NULL , 
	WFSCRP DECIMAL(5, 2) NOT NULL , 
	WFRETN DECIMAL(5, 2) NOT NULL , 
	WFAVRG DECIMAL(15, 5) NOT NULL , 
	WFBGQT DECIMAL(15, 4) NOT NULL , 
	WFBGAT DECIMAL(15, 0) NOT NULL , 
	WFINQT DECIMAL(15, 4) NOT NULL , 
	WFINAT DECIMAL(15, 0) NOT NULL , 
	WFUSQT1 DECIMAL(15, 4) NOT NULL , 
	WFUSAT1 DECIMAL(15, 0) NOT NULL , 
	WFUSQT2 DECIMAL(15, 4) NOT NULL , 
	WFUSAT2 DECIMAL(15, 0) NOT NULL , 
	WFUSQT3 DECIMAL(15, 4) NOT NULL , 
	WFUSAT3 DECIMAL(15, 0) NOT NULL , 
	WFOHQT DECIMAL(15, 4) NOT NULL , 
	WFOHAT DECIMAL(15, 0) NOT NULL , 
	WFPHQT DECIMAL(15, 4) NOT NULL , 
	WFPHAT DECIMAL(15, 0) NOT NULL , 
	WFDEFQT DECIMAL(15, 4) NOT NULL , 
	WFDEFAT DECIMAL(15, 0) NOT NULL , 
	WFLAUTQT DECIMAL(15, 4) NOT NULL , 
	WFLAUTAT DECIMAL(15, 0) NOT NULL , 
	WFRAUTQT DECIMAL(15, 4) NOT NULL , 
	WFRAUTAT DECIMAL(15, 0) NOT NULL , 
	WFCLQT DECIMAL(15, 4) NOT NULL , 
	WFCLAT DECIMAL(15, 0) NOT NULL , 
	WFPLAN CHAR(2) CCSID 833 NOT NULL , 
	WFSTSCD CHAR(1) CCSID 833 NOT NULL , 
	WFIPADDR CHAR(30) CCSID 933 NOT NULL , 
	WFMACADDR CHAR(30) CCSID 933 NOT NULL , 
	WFINPTDT CHAR(8) CCSID 933 NOT NULL , 
	WFUPDTDT CHAR(8) CCSID 933 NOT NULL , 
	PRIMARY KEY( WFCMCD , WFYEAR , WFMONTH , WFPLANT , WFDVSN , WFIOCD, WFVENDOR , WFITNO ) ) ;
	
INSERT INTO PBWIP.WIP009
( WFYEAR,WFMONTH,WFCMCD,WFPLANT,WFDVSN,WFIOCD,WFVENDOR,WFITNO,WFUNIT,WFSCRP,WFRETN,WFAVRG,WFBGQT,
WFBGAT,WFINQT,WFINAT,WFUSQT1,WFUSAT1,WFUSQT2,WFUSAT2,WFUSQT3,WFUSAT3,WFOHQT,WFOHAT,WFPHQT,WFPHAT,
WFDEFQT,WFDEFAT,WFLAUTQT,WFLAUTAT,WFRAUTQT,WFRAUTAT,WFCLQT,WFCLAT,WFPLAN,WFSTSCD,
WFIPADDR,WFMACADDR,WFINPTDT,WFUPDTDT )

SELECT WFYEAR,WFMONTH,WFCMCD,WFPLANT,WFDVSN,'2',WFVENDOR,WFITNO,WFUNIT,WFSCRP,WFRETN,WFAVRG,WFBGQT,
WFBGAT,WFINQT,WFINAT,WFUSQT1,WFUSAT1,WFUSQT2,WFUSAT2,WFUSQT3,WFUSAT3,WFOHQT,WFOHAT,WFPHQT,WFPHAT,
WFDEFQT,WFDEFAT,WFLAUTQT,WFLAUTAT,WFRAUTQT,WFRAUTAT,WFCLQT,WFCLAT,WFPLAN,WFSTSCD,
WFIPADDR,WFMACADDR,WFINPTDT,WFUPDTDT
FROM PBWIP.WIP009BK;