/************************************************************************************************/
/*	File Name	: sp_eisq080i_01.SQL                                                            */
/*	SYSTEM		: 경영자용 통합정보	                                                            */
/*	Description	: 전사 일별 FTTQ 현황			                                                */
/*	Supply		: DAEWOO Information Systems Co., LTD IAS Dept                                  */
/*	Use DataBase: IPIS2000                                                                      */
/*	Use Table	: TQPROGRESSBADMASTER                                                           */
/*                TQPROGRESSBADDETAIL                                                           */
/*  Parameter   : @ps_QCDateFm          char(10)    => 조회일자FROM                             */
/*                @ps_QCDateTo          char(10)    => 조회일자TO                               */
/*	Notes		: 전사 일별 FTTQ현황 자료를 조회한다.  		                                    */
/*	Made Date	: 2002. 12. 03                                                                  */
/*	Author		: 대우정보-유종희                                                               */
/************************************************************************************************/
if exists (select * from sysobjects where id = object_id('dbo.sp_eisq080i_01') and sysstat & 0xf = 4)
	drop procedure dbo.sp_eisq080i_01
GO
/*
Exec sp_eisq080i_01
        @ps_QCDateFm        = '2002.12.01',
        @ps_QCDateTo        = '2002.12.31'

*/

/****** Object:  Stored Procedure dbo.sp_eisq080i_01    Script Date: 02-09-01  ******/
CREATE PROCEDURE sp_eisq080i_01
        @ps_QCDateFm          char(10)      ,   -- 조회일자FROM
        @ps_QCDateTo          char(10)          -- 조회일자TO

AS

BEGIN

	SELECT AS_AREACODE		,
	       AS_DIVISIONCODE	,
		   A.AREANAME				AS AS_AREANAME,
		   B.DIVISIONNAME			AS AS_DIVISIONNAME,
		   SUM(ISNULL(M_S01, 0))	AS I_01,
		   SUM(ISNULL(M_S02, 0))	AS I_02,
		   SUM(ISNULL(M_S03, 0))	AS I_03,
		   SUM(ISNULL(M_S04, 0))	AS I_04,
		   SUM(ISNULL(M_S05, 0))	AS I_05,
		   SUM(ISNULL(M_S06, 0))	AS I_06,
		   SUM(ISNULL(M_S07, 0))	AS I_07,
		   SUM(ISNULL(M_S08, 0))	AS I_08,
		   SUM(ISNULL(M_S09, 0))	AS I_09,
		   SUM(ISNULL(M_S10, 0))	AS I_10,
		   SUM(ISNULL(M_S11, 0))	AS I_11,
		   SUM(ISNULL(M_S12, 0))	AS I_12,
		   SUM(ISNULL(M_S13, 0))	AS I_13,
		   SUM(ISNULL(M_S14, 0))	AS I_14,
		   SUM(ISNULL(M_S15, 0))	AS I_15,
		   SUM(ISNULL(M_S16, 0))	AS I_16,
		   SUM(ISNULL(M_S17, 0))	AS I_17,
		   SUM(ISNULL(M_S18, 0))	AS I_18,
		   SUM(ISNULL(M_S19, 0))	AS I_19,
		   SUM(ISNULL(M_S20, 0))	AS I_20,
		   SUM(ISNULL(M_S21, 0))	AS I_21,
		   SUM(ISNULL(M_S22, 0))	AS I_22,
		   SUM(ISNULL(M_S23, 0))	AS I_23,
		   SUM(ISNULL(M_S24, 0))	AS I_24,
		   SUM(ISNULL(M_S25, 0))	AS I_25,
		   SUM(ISNULL(M_S26, 0))	AS I_26,
		   SUM(ISNULL(M_S27, 0))	AS I_27,
		   SUM(ISNULL(M_S28, 0))	AS I_28,
		   SUM(ISNULL(M_S29, 0))	AS I_29,
		   SUM(ISNULL(M_S30, 0))	AS I_30,
		   SUM(ISNULL(M_S31, 0))	AS I_31,
		   SUM(ISNULL(M_STOT, 0))	AS I_32,
		   SUM(ISNULL(D_B01, 0))	AS B_01,
		   SUM(ISNULL(D_B01, 0))	AS B_02,
		   SUM(ISNULL(D_B01, 0))	AS B_03,
		   SUM(ISNULL(D_B01, 0))	AS B_04,
		   SUM(ISNULL(D_B01, 0))	AS B_05,
		   SUM(ISNULL(D_B01, 0))	AS B_06,
		   SUM(ISNULL(D_B01, 0))	AS B_07,
		   SUM(ISNULL(D_B01, 0))	AS B_08,
		   SUM(ISNULL(D_B01, 0))	AS B_09,
		   SUM(ISNULL(D_B01, 0))	AS B_10,
		   SUM(ISNULL(D_B01, 0))	AS B_11,
		   SUM(ISNULL(D_B01, 0))	AS B_12,
		   SUM(ISNULL(D_B01, 0))	AS B_13,
		   SUM(ISNULL(D_B01, 0))	AS B_14,
		   SUM(ISNULL(D_B01, 0))	AS B_15,
		   SUM(ISNULL(D_B01, 0))	AS B_16,
		   SUM(ISNULL(D_B01, 0))	AS B_17,
		   SUM(ISNULL(D_B01, 0))	AS B_18,
		   SUM(ISNULL(D_B01, 0))	AS B_19,
		   SUM(ISNULL(D_B01, 0))	AS B_20,
		   SUM(ISNULL(D_B01, 0))	AS B_21,
		   SUM(ISNULL(D_B01, 0))	AS B_22,
		   SUM(ISNULL(D_B01, 0))	AS B_23,
		   SUM(ISNULL(D_B01, 0))	AS B_24,
		   SUM(ISNULL(D_B01, 0))	AS B_25,
		   SUM(ISNULL(D_B01, 0))	AS B_26,
		   SUM(ISNULL(D_B01, 0))	AS B_27,
		   SUM(ISNULL(D_B01, 0))	AS B_28,
		   SUM(ISNULL(D_B01, 0))	AS B_29,
		   SUM(ISNULL(D_B01, 0))	AS B_30,
		   SUM(ISNULL(D_B01, 0))	AS B_31,
		   SUM(ISNULL(D_BTOT, 0))	AS B_32
	  FROM (
			-- 공정불량마스타
			--
	  		SELECT A.AREACODE					AS AS_AREACODE,
	               A.DIVISIONCODE				AS AS_DIVISIONCODE,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.01'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S01,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.02'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S02,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.03'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S03,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.04'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S04,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.05'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S05,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.06'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S06,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.07'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S07,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.08'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S08,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.09'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S09,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.10'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S10,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.11'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S11,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.12'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S12,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.13'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S13,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.14'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S14,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.15'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S15,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.16'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S16,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.17'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S17,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.18'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S18,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.19'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S19,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.20'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S20,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.21'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S21,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.22'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S22,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.23'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S23,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.24'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S24,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.25'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S25,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.26'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S26,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.27'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S27,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.28'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S28,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.29'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S29,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.30'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S30,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.31'= A.ORIGINATIONDATE THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_S31,
				   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7)        = SUBSTRING(A.ORIGINATIONDATE,1,7) THEN SUM(A.PRODUCTQTY) ELSE 0 END AS M_STOT,
				   0 AS D_B01,
				   0 AS D_B02,
				   0 AS D_B03,
				   0 AS D_B04,
				   0 AS D_B05,
				   0 AS D_B06,
				   0 AS D_B07,
				   0 AS D_B08,
				   0 AS D_B09,
				   0 AS D_B10,
				   0 AS D_B11,
				   0 AS D_B12,
				   0 AS D_B13,
				   0 AS D_B14,
				   0 AS D_B15,
				   0 AS D_B16,
				   0 AS D_B17,
				   0 AS D_B18,
				   0 AS D_B19,
				   0 AS D_B20,
				   0 AS D_B21,
				   0 AS D_B22,
				   0 AS D_B23,
				   0 AS D_B24,
				   0 AS D_B25,
				   0 AS D_B26,
				   0 AS D_B27,
				   0 AS D_B28,
				   0 AS D_B29,
				   0 AS D_B30,
				   0 AS D_B31,
				   0 AS D_BTOT
			  FROM TQPROGRESSBADMASTER  A
			 WHERE A.ORIGINATIONDATE >= @ps_QCDateFm
			   AND A.ORIGINATIONDATE <= @ps_QCDateTo
			 GROUP BY A.AREACODE, A.DIVISIONCODE, A.ORIGINATIONDATE
		
			UNION ALL
		
			-- 공정불량디테일
			--
			SELECT A.AREACODE			AS AS_AREACODE,
	               A.DIVISIONCODE		AS AS_DIVISIONCODE,
			 	   0 AS M_S01,
			 	   0 AS M_S02,
			 	   0 AS M_S03,
			 	   0 AS M_S04,
			 	   0 AS M_S05,
			 	   0 AS M_S06,
			 	   0 AS M_S07,
			 	   0 AS M_S08,
			 	   0 AS M_S09,
			 	   0 AS M_S10,
			 	   0 AS M_S11,
			 	   0 AS M_S12,
			 	   0 AS M_S13,
			 	   0 AS M_S14,
			 	   0 AS M_S15,
			 	   0 AS M_S16,
			 	   0 AS M_S17,
			 	   0 AS M_S18,
			 	   0 AS M_S19,
			 	   0 AS M_S20,
			 	   0 AS M_S21,
			 	   0 AS M_S22,
			 	   0 AS M_S23,
			 	   0 AS M_S24,
			 	   0 AS M_S25,
			 	   0 AS M_S26,
			 	   0 AS M_S27,
			 	   0 AS M_S28,
			 	   0 AS M_S29,
			 	   0 AS M_S30,
			 	   0 AS M_S31,
			 	   0 AS M_STOT,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.01'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B01,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.02'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B02,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.03'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B03,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.04'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B04,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.05'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B05,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.06'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B06,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.07'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B07,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.08'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B08,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.09'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B09,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.10'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B10,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.11'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B11,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.12'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B12,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.13'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B13,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.14'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B14,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.15'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B15,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.16'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B16,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.17'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B17,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.18'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B18,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.19'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B19,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.20'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B20,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.21'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B21,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.22'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B22,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.23'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B23,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.24'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B24,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.25'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B25,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.26'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B26,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.27'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B27,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.28'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B28,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.29'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B29,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.30'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B30,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7) + '.31'= A.ORIGINATIONDATE THEN SUM(A.TOTALQTY) ELSE 0 END AS D_B31,
			 	   CASE WHEN SUBSTRING(@ps_QCDateFm,1,7)        = SUBSTRING(A.ORIGINATIONDATE,1,7) THEN SUM(A.TOTALQTY) ELSE 0 END AS D_BTOT
			  FROM TQPROGRESSBADDETAIL  A                                                                                                                                                           
			 WHERE A.ORIGINATIONDATE >= @ps_QCDateFm
			   AND A.ORIGINATIONDATE <= @ps_QCDateTo
			 GROUP BY A.AREACODE, A.DIVISIONCODE, A.ORIGINATIONDATE
		   ) TMP, TMSTAREA A, TMSTDIVISION B
	 WHERE RTRIM(AS_AREACODE)		= A.AREACODE
	   AND RTRIM(AS_AREACODE)		= B.AREACODE
	   AND RTRIM(AS_DIVISIONCODE)	= B.DIVISIONCODE
	 GROUP BY AS_AREACODE, AS_DIVISIONCODE, A.AREANAME, B.DIVISIONNAME, B.SORTORDER
	 ORDER BY AS_AREACODE, B.SORTORDER

END 

go
