--  Generate SQL
--  Version:                    V5R3M0 040528
--  Generated on:               09/06/22 12:01:56
--  Relational Database:        I520
--  Standards Option:           DB2 UDB iSeries
--  Description :               IPIS mh SUMMARY For WORKCENTER

DROP TABLE TMHBASEWORKCENTER;

CREATE TABLE TMHBASEWORKCENTER (
  ZCMCD CHAR(2) NOT NULL DEFAULT '' ,       -- 회사
  ZDATE CHAR(8) NOT NULL DEFAULT '' ,       -- 년월일
  AREACODE CHAR(1)   NOT NULL DEFAULT '' ,      -- 지역
  DIVISIONCODE CHAR(1)   NOT NULL DEFAULT '' ,  -- 공장
  ITEMCODE VARCHAR(12)   NOT NULL DEFAULT '' ,    -- 품번
  SUBLINECODE VARCHAR(7) NOT NULL DEFAULT '',  -- 대체라인
  SUBLINENO CHAR(1)   NOT NULL DEFAULT '' ,      -- 라인넘버
  WORKCENTER VARCHAR(5)   NOT NULL DEFAULT '' ,      -- 조코드
  PRODUCTQTY  INTEGER NOT NULL DEFAULT 0,          -- 생산량
  STDSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 표준MH
  ACTSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 투입MH
  POWERSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 당 소비전력
  MACTIMESUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 당 기계작업시간
  AVGSTDSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 표준MH
  AVGACTSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 투입MH
  AVGPOWERSUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 당 소비전력
  AVGMACTIMESUM DECIMAL(12,6) NOT NULL DEFAULT 0.000000 ,  -- 당 기계작업시간
  PRIMARY KEY( ZCMCD , ZDATE , AREACODE, DIVISIONCODE, ITEMCODE, SUBLINECODE, SUBLINENO, WORKCENTER ) );
  
ALTER TABLE [dbo].[TMHBASEWORKCENTER] ADD [LastDate] [LastDate] NULL;
