$PBExportHeader$w_wip_backup.srw
$PBExportComments$재공 Data Migration Window
forward
global type w_wip_backup from w_origin_sheet01
end type
type dw_1 from datawindow within w_wip_backup
end type
type cb_1 from commandbutton within w_wip_backup
end type
type cb_2 from commandbutton within w_wip_backup
end type
type cb_3 from commandbutton within w_wip_backup
end type
type cb_4 from commandbutton within w_wip_backup
end type
type cb_5 from commandbutton within w_wip_backup
end type
type dw_2 from datawindow within w_wip_backup
end type
type gb_2 from groupbox within w_wip_backup
end type
end forward

global type w_wip_backup from w_origin_sheet01
dw_1 dw_1
cb_1 cb_1
cb_2 cb_2
cb_3 cb_3
cb_4 cb_4
cb_5 cb_5
dw_2 dw_2
gb_2 gb_2
end type
global w_wip_backup w_wip_backup

forward prototypes
public function integer wf_wip002_vndr (string ag_div, string ag_yyyy, string ag_mm)
public function integer wf_wip002_line (string ag_div, string ag_yyyy, string ag_mm)
public function integer wf_update_orct (string ag_cmcd, string ag_plant, string ag_dvsn, string ag_yyyymm)
public function integer wf_wip001_orct (string ag_cmcd, string ag_plant, string ag_dvsn)
public function integer wf_wip001_line (string ag_div)
public function integer wf_wip001_vndr (string ag_div)
end prototypes

public function integer wf_wip002_vndr (string ag_div, string ag_yyyy, string ag_mm);//업체데이타 인서트(wipdaw -> wip002)
choose case ag_mm
	case '01'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )  
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG1",    0,  "WCBQT1", "WCBAT1",   0,  "WCINQTA1","WCINATA1",  0, "WCINATB1", 0,  
				   0 ,          0,"WCUSQTA1","WCUSATA1",  0,      0,        0,        0, 
				   0,          0,   0,       0,  "WCUSQTD1","WCUSATD1","WCUSQTE1","WCUSATE1",  0, 
				 "WCUSQTF1","WCUSATF1", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT1" = 0 AND "WCBAT1" = 0  AND "WCINQTA1" = 0 AND "WCUSQTA1" = 0 AND "WCUSQTB1" = 0
						AND "WCUSQTC1" = 0 AND "WCUSQTD1" = 0 AND "WCUSQTE1" = 0 AND "WCUSQTF1" = 0)
			using sqlca;
	case '02'	
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG2",    0,  "WCBQT2", "WCBAT2",   0,  "WCINQTA2","WCINATA2",  0, "WCINATB2", 0,  
				 0,0,"WCUSQTA2","WCUSATA2",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD2","WCUSATD2","WCUSQTE2","WCUSATE2",  0, 
				 "WCUSQTF2","WCUSATF2", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT2" = 0 AND "WCBAT2" = 0  AND "WCINQTA2" = 0 AND "WCUSQTA2" = 0 AND "WCUSQTB2" = 0
						AND "WCUSQTC2" = 0 AND "WCUSQTD2" = 0 AND "WCUSQTE2" = 0 AND "WCUSQTF2" = 0) 
			using sqlca;
	case '03'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG3",    0,  "WCBQT3", "WCBAT3",   0,  "WCINQTA3","WCINATA3",  0, "WCINATB3", 0,  
				 0,0,"WCUSQTA3","WCUSATA3",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD3","WCUSATD3","WCUSQTE3","WCUSATE3",  0, 
				 "WCUSQTF3","WCUSATF3", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT3" = 0 AND "WCBAT3" = 0  AND "WCINQTA3" = 0 AND "WCUSQTA3" = 0 AND "WCUSQTB3" = 0
						AND "WCUSQTC3" = 0 AND "WCUSQTD3" = 0 AND "WCUSQTE3" = 0 AND "WCUSQTF3" = 0)  
			using sqlca;
	case '04'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG4",    0,  "WCBQT4", "WCBAT4",   0,  "WCINQTA4","WCINATA4",  0, "WCINATB4", 0,  
				 0,0,"WCUSQTA4","WCUSATA4",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD4","WCUSATD4","WCUSQTE4","WCUSATE4",  0, 
				 "WCUSQTF4","WCUSATF4", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT4" = 0 AND "WCBAT4" = 0  AND "WCINQTA4" = 0 AND "WCUSQTA4" = 0 AND "WCUSQTB4" = 0
						AND "WCUSQTC4" = 0 AND "WCUSQTD4" = 0 AND "WCUSQTE4" = 0 AND "WCUSQTF4" = 0) 
			using sqlca;
	case '05'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG5",    0,  "WCBQT5", "WCBAT5",   0,  "WCINQTA5","WCINATA5",  0, "WCINATB5", 0,  
				 0,0,"WCUSQTA5","WCUSATA5",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD5","WCUSATD5","WCUSQTE5","WCUSATE5",  0, 
				 "WCUSQTF5","WCUSATF5", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT5" = 0 AND "WCBAT5" = 0  AND "WCINQTA5" = 0 AND "WCUSQTA5" = 0 AND "WCUSQTB5" = 0
						AND "WCUSQTC5" = 0 AND "WCUSQTD5" = 0 AND "WCUSQTE5" = 0 AND "WCUSQTF5" = 0)  
			using sqlca;
	case '06'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG6",    0,  "WCBQT6", "WCBAT6",   0,  "WCINQTA6","WCINATA6",  0, "WCINATB6", 0,  
				 0,0,"WCUSQTA6","WCUSATA6",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD6","WCUSATD6","WCUSQTE6","WCUSATE6",  0, 
				 "WCUSQTF6","WCUSATF6", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT6" = 0 AND "WCBAT6" = 0  AND "WCINQTA6" = 0 AND "WCUSQTA6" = 0 AND "WCUSQTB6" = 0
						AND "WCUSQTC6" = 0 AND "WCUSQTD6" = 0 AND "WCUSQTE6" = 0 AND "WCUSQTF6" = 0)  
			using sqlca;
	case '07'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG7",    0,  "WCBQT7", "WCBAT7",   0,  "WCINQTA7","WCINATA7",  0, "WCINATB7", 0,  
				 0,0,"WCUSQTA7","WCUSATA7",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD7","WCUSATD7","WCUSQTE7","WCUSATE7",  0, 
				 "WCUSQTF7","WCUSATF7", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT7" = 0 AND "WCBAT7" = 0  AND "WCINQTA7" = 0 AND "WCUSQTA7" = 0 AND "WCUSQTB7" = 0
						AND "WCUSQTC7" = 0 AND "WCUSQTD7" = 0 AND "WCUSQTE7" = 0 AND "WCUSQTF7" = 0)  
			using sqlca;
	case '08'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG8",    0,  "WCBQT8", "WCBAT8",   0,  "WCINQTA8","WCINATA8",  0, "WCINATB8", 0,  
				 0,0,"WCUSQTA8","WCUSATA8",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD8","WCUSATD8","WCUSQTE8","WCUSATE8",  0, 
				 "WCUSQTF8","WCUSATF8", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT8" = 0 AND "WCBAT8" = 0  AND "WCINQTA8" = 0 AND "WCUSQTA8" = 0 AND "WCUSQTB8" = 0
						AND "WCUSQTC8" = 0 AND "WCUSQTD8" = 0 AND "WCUSQTE8" = 0 AND "WCUSQTF8" = 0)  
			using sqlca;
	case '09'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG9",    0,  "WCBQT9", "WCBAT9",   0,  "WCINQTA9","WCINATA9",  0, "WCINATB9", 0,  
				 0,0,"WCUSQTA9","WCUSATA9",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD9","WCUSATD9","WCUSQTE9","WCUSATE9",  0, 
				 "WCUSQTF9","WCUSATF9", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT9" = 0 AND "WCBAT9" = 0  AND "WCINQTA9" = 0 AND "WCUSQTA9" = 0 AND "WCUSQTB9" = 0
						AND "WCUSQTC9" = 0 AND "WCUSQTD9" = 0 AND "WCUSQTE9" = 0 AND "WCUSQTF9" = 0)   
			using sqlca;
	case '10'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG10",    0,  "WCBQT10", "WCBAT10",   0,  "WCINQTA10","WCINATA10",  0, "WCINATB10", 0,  
				 0,0,"WCUSQTA10","WCUSATA10",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD10","WCUSATD10","WCUSQTE10","WCUSATE10",  0, 
				 "WCUSQTF10","WCUSATF10", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' )  
			using sqlca;
	case '11'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG11",    0,  "WCBQT11", "WCBAT11",   0,  "WCINQTA11","WCINATA11",  0, "WCINATB11", 0,  
				 0,0,"WCUSQTA11","WCUSATA11",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD11","WCUSATD11","WCUSQTE11","WCUSATE11",  0, 
				 "WCUSQTF11","WCUSATF11", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) 
			using sqlca;
	case '12'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG12",    0,  "WCBQT12", "WCBAT12",   0,  "WCINQTA12","WCINATA12",  0, "WCINATB12", 0,  
				 0,0,"WCUSQTA12","WCUSATA12",  0,      0,        0,        0, 
				 0,0,   0,       0,  "WCUSQTD12","WCUSATD12","WCUSQTE12","WCUSATE12",  0, 
				 "WCUSQTF12","WCUSATF12", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
					NOT("WCBQT12" = 0 AND "WCBAT12" = 0  AND "WCINQTA12" = 0 AND "WCUSQTA12" = 0 AND "WCUSQTB12" = 0
						AND "WCUSQTC12" = 0 AND "WCUSQTD12" = 0 AND "WCUSQTE12" = 0 AND "WCUSQTF12" = 0)   
			using sqlca;
end choose

if sqlca.sqlcode <> 0 then
	return -1
else
	return 0
end if
end function

public function integer wf_wip002_line (string ag_div, string ag_yyyy, string ag_mm);//라인데이타 인서트(wipdaw -> wip002)
choose case ag_mm
	case '01'
		//라인
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )  
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG1",    0,  "WCBQT1", "WCBAT1",   0,  "WCINQTA1","WCINATA1",  0, "WCINATB1", 0,  
				 "WCUSQTA1","WCUSATA1","WCUSQTC1","WCUSATC1",  0,      0,        0,        0, 
				 "WCUSQTB1","WCUSATB1",   0,       0,  "WCUSQTD1","WCUSATD1","WCUSQTE1","WCUSATE1",  0, 
				 "WCUSQTF1","WCUSATF1", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT1" = 0 AND "WCBAT1" = 0  AND "WCINQTA1" = 0 AND "WCUSQTA1" = 0 AND "WCUSQTB1" = 0
						AND "WCUSQTC1" = 0 AND "WCUSQTD1" = 0 AND "WCUSQTE1" = 0 AND "WCUSQTF1" = 0)
			using sqlca;
	case '02'	
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG2",    0,  "WCBQT2", "WCBAT2",   0,  "WCINQTA2","WCINATA2",  0, "WCINATB2", 0,  
				 "WCUSQTA2","WCUSATA2","WCUSQTC2","WCUSATC2",  0,      0,        0,        0, 
				 "WCUSQTB2","WCUSATB2",   0,       0,  "WCUSQTD2","WCUSATD2","WCUSQTE2","WCUSATE2",  0, 
				 "WCUSQTF2","WCUSATF2", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT2" = 0 AND "WCBAT2" = 0  AND "WCINQTA2" = 0 AND "WCUSQTA2" = 0 AND "WCUSQTB2" = 0
						AND "WCUSQTC2" = 0 AND "WCUSQTD2" = 0 AND "WCUSQTE2" = 0 AND "WCUSQTF2" = 0) 
			using sqlca;
	case '03'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG3",    0,  "WCBQT3", "WCBAT3",   0,  "WCINQTA3","WCINATA3",  0, "WCINATB3", 0,  
				 "WCUSQTA3","WCUSATA3","WCUSQTC3","WCUSATC3",  0,      0,        0,        0, 
				 "WCUSQTB3","WCUSATB3",   0,       0,  "WCUSQTD3","WCUSATD3","WCUSQTE3","WCUSATE3",  0, 
				 "WCUSQTF3","WCUSATF3", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT3" = 0 AND "WCBAT3" = 0  AND "WCINQTA3" = 0 AND "WCUSQTA3" = 0 AND "WCUSQTB3" = 0
						AND "WCUSQTC3" = 0 AND "WCUSQTD3" = 0 AND "WCUSQTE3" = 0 AND "WCUSQTF3" = 0)  
			using sqlca;
	case '04'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG4",    0,  "WCBQT4", "WCBAT4",   0,  "WCINQTA4","WCINATA4",  0, "WCINATB4", 0,  
				 "WCUSQTA4","WCUSATA4","WCUSQTC4","WCUSATC4",  0,      0,        0,        0, 
				 "WCUSQTB4","WCUSATB4",   0,       0,  "WCUSQTD4","WCUSATD4","WCUSQTE4","WCUSATE4",  0, 
				 "WCUSQTF4","WCUSATF4", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT4" = 0 AND "WCBAT4" = 0  AND "WCINQTA4" = 0 AND "WCUSQTA4" = 0 AND "WCUSQTB4" = 0
						AND "WCUSQTC4" = 0 AND "WCUSQTD4" = 0 AND "WCUSQTE4" = 0 AND "WCUSQTF4" = 0) 
			using sqlca;
	case '05'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG5",    0,  "WCBQT5", "WCBAT5",   0,  "WCINQTA5","WCINATA5",  0, "WCINATB5", 0,  
				 "WCUSQTA5","WCUSATA5","WCUSQTC5","WCUSATC5",  0,      0,        0,        0, 
				 "WCUSQTB5","WCUSATB5",   0,       0,  "WCUSQTD5","WCUSATD5","WCUSQTE5","WCUSATE5",  0, 
				 "WCUSQTF5","WCUSATF5", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT5" = 0 AND "WCBAT5" = 0  AND "WCINQTA5" = 0 AND "WCUSQTA5" = 0 AND "WCUSQTB5" = 0
						AND "WCUSQTC5" = 0 AND "WCUSQTD5" = 0 AND "WCUSQTE5" = 0 AND "WCUSQTF5" = 0)  
			using sqlca;
	case '06'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG6",    0,  "WCBQT6", "WCBAT6",   0,  "WCINQTA6","WCINATA6",  0, "WCINATB6", 0,  
				 "WCUSQTA6","WCUSATA6","WCUSQTC6","WCUSATC6",  0,      0,        0,        0, 
				 "WCUSQTB6","WCUSATB6",   0,       0,  "WCUSQTD6","WCUSATD6","WCUSQTE6","WCUSATE6",  0, 
				 "WCUSQTF6","WCUSATF6", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT6" = 0 AND "WCBAT6" = 0  AND "WCINQTA6" = 0 AND "WCUSQTA6" = 0 AND "WCUSQTB6" = 0
						AND "WCUSQTC6" = 0 AND "WCUSQTD6" = 0 AND "WCUSQTE6" = 0 AND "WCUSQTF6" = 0)  
			using sqlca;
	case '07'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG7",    0,  "WCBQT7", "WCBAT7",   0,  "WCINQTA7","WCINATA7",  0, "WCINATB7", 0,  
				 "WCUSQTA7","WCUSATA7","WCUSQTC7","WCUSATC7",  0,      0,        0,        0, 
				 "WCUSQTB7","WCUSATB7",   0,       0,  "WCUSQTD7","WCUSATD7","WCUSQTE7","WCUSATE7",  0, 
				 "WCUSQTF7","WCUSATF7", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT7" = 0 AND "WCBAT7" = 0  AND "WCINQTA7" = 0 AND "WCUSQTA7" = 0 AND "WCUSQTB7" = 0
						AND "WCUSQTC7" = 0 AND "WCUSQTD7" = 0 AND "WCUSQTE7" = 0 AND "WCUSQTF7" = 0)  
			using sqlca;
	case '08'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG8",    0,  "WCBQT8", "WCBAT8",   0,  "WCINQTA8","WCINATA8",  0, "WCINATB8", 0,  
				 "WCUSQTA8","WCUSATA8","WCUSQTC8","WCUSATC8",  0,      0,        0,        0, 
				 "WCUSQTB8","WCUSATB8",   0,       0,  "WCUSQTD8","WCUSATD8","WCUSQTE8","WCUSATE8",  0, 
				 "WCUSQTF8","WCUSATF8", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT8" = 0 AND "WCBAT8" = 0  AND "WCINQTA8" = 0 AND "WCUSQTA8" = 0 AND "WCUSQTB8" = 0
						AND "WCUSQTC8" = 0 AND "WCUSQTD8" = 0 AND "WCUSQTE8" = 0 AND "WCUSQTF8" = 0)  
			using sqlca;
	case '09'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG9",    0,  "WCBQT9", "WCBAT9",   0,  "WCINQTA9","WCINATA9",  0, "WCINATB9", 0,  
				 "WCUSQTA9","WCUSATA9","WCUSQTC9","WCUSATC9",  0,      0,        0,        0, 
				 "WCUSQTB9","WCUSATB9",   0,       0,  "WCUSQTD9","WCUSATD9","WCUSQTE9","WCUSATE9",  0, 
				 "WCUSQTF9","WCUSATF9", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT9" = 0 AND "WCBAT9" = 0  AND "WCINQTA9" = 0 AND "WCUSQTA9" = 0 AND "WCUSQTB9" = 0
						AND "WCUSQTC9" = 0 AND "WCUSQTD9" = 0 AND "WCUSQTE9" = 0 AND "WCUSQTF9" = 0)   
			using sqlca;
	case '10'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG10",    0,  "WCBQT10", "WCBAT10",   0,  "WCINQTA10","WCINATA10",  0, "WCINATB10", 0,  
				 "WCUSQTA10","WCUSATA10","WCUSQTC10","WCUSATC10",  0,      0,        0,        0, 
				 "WCUSQTB10","WCUSATB10",      0,      0,  "WCUSQTD10","WCUSATD10","WCUSQTE10","WCUSATE10",  0, 
				 "WCUSQTF10","WCUSATF10", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' )  
			using sqlca;
	case '11'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG11",    0,  "WCBQT11", "WCBAT11",   0,  "WCINQTA11","WCINATA11",  0, "WCINATB11", 0,  
				 "WCUSQTA11","WCUSATA11","WCUSQTC11","WCUSATC11",  0,      0,        0,        0, 
				 "WCUSQTB11","WCUSATB11",   0,       0,  "WCUSQTD11","WCUSATD11","WCUSQTE11","WCUSATE11",  0, 
				 "WCUSQTF11","WCUSATF11", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy )  AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' )  
			using sqlca;
	case '12'
		INSERT INTO "PBWIP"."WIP002"  
			( "WBCMCD","WBPLANT","WBDVSN","WBORCT","WBITNO","WBYEAR","WBMONTH","WBREV","WBIOCD","WBITCL",   
			  "WBSRCE","WBPDCD","WBUNIT","WBTYPE","WBDESC","WBSPEC","WBSCRP","WBRETN",   
			  "WBAVRG1","WBAVRG2","WBBGQT","WBBGAT1","WBBGAT2","WBINQT","WBINAT1","WBINAT2","WBINAT3","WBINAT4",   
			  "WBUSQT1","WBUSAT1","WBUSQT2","WBUSAT2","WBUSQT3","WBUSAT3","WBUSQT4","WBUSAT4",   
			  "WBUSQT5","WBUSAT5","WBUSQT6","WBUSAT6","WBUSQT7","WBUSAT7","WBUSQT8","WBUSAT8","WBUSAT9",   
			  "WBUSQTA","WBUSATA","WBPLAN","WBIPADDR","WBMACADDR","WBINPTDT","WBUPDTDT" )
		SELECT '01',    'D' ,    "WCDIV","WCORCT","WCITNO","WCYEARC"||"WCYEARY", :ag_mm ,"WCREV","WCIOCD","WCCLAS",   
				 "WCSRC",SUBSTR("WCPDCD",1,2),"WCUM", "WCTYP", "WCDSP", "WCSPC", "WCSCRP", "WCRETN",   
				 "WCAVG12",    0,  "WCBQT12", "WCBAT12",   0,  "WCINQTA12","WCINATA12",  0, "WCINATB12", 0,  
				 "WCUSQTA12","WCUSATA12","WCUSQTC12","WCUSATC12",  0,      0,        0,        0, 
				 "WCUSQTB12","WCUSATB12",   0,       0,  "WCUSQTD12","WCUSATD12","WCUSQTE12","WCUSATE12",  0, 
				 "WCUSQTF12","WCUSATF12", ' ', ' ', ' ', ' ', ' '
			FROM "DEINVO"."WIPDAW"  
			WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ag_div ) AND  
					( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ag_yyyy ) AND
					( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
					NOT("WCBQT12" = 0 AND "WCBAT12" = 0  AND "WCINQTA12" = 0 AND "WCUSQTA12" = 0 AND "WCUSQTB12" = 0
						AND "WCUSQTC12" = 0 AND "WCUSQTD12" = 0 AND "WCUSQTE12" = 0 AND "WCUSQTF12" = 0)   
			using sqlca;
end choose

if sqlca.sqlcode <> 0 then
	return -1
else
	return 0
end if
end function

public function integer wf_update_orct (string ag_cmcd, string ag_plant, string ag_dvsn, string ag_yyyymm);string ls_itno, ls_orct, ls_mm
dec{4} lc_bgqt, lc_inqt, lc_usqt1, lc_usqt2,lc_usqt5,lc_usqt7, lc_usqt8, lc_usqta
dec{0} lc_bgamt, lc_inamt1, lc_inamt2,lc_usamt1, lc_usamt2, lc_usamt5, lc_usamt7, lc_usamt8, lc_usamta
ls_mm = mid(ag_yyyymm,5)
declare upitem_cur cursor for  
	SELECT "WBITNO","WBORCT" FROM "PBWIP"."WIP002"  
   WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
         ( "PBWIP"."WIP002"."WBPLANT" = :ag_plant ) AND  
         ( "PBWIP"."WIP002"."WBDVSN" = :ag_dvsn ) AND  
         ( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ag_yyyymm ) AND  
         ( "PBWIP"."WIP002"."WBIOCD" = '1' )   
         using sqlca;
	
open upitem_cur;	
	do while true
		fetch upitem_cur into :ls_itno,:ls_orct ;
			if sqlca.sqlcode <> 0 then
				exit
			end if
		UPDATE "PBWIP"."WIP002"  
   		SET "WBORCT" = '9999'  
   		WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
         		( "PBWIP"."WIP002"."WBPLANT" = :ag_plant ) AND  
         		( "PBWIP"."WIP002"."WBDVSN" = :ag_dvsn ) AND
					( "PBWIP"."WIP002"."WBITNO" = :ls_itno ) AND 
					( "PBWIP"."WIP002"."WBORCT" = :ls_orct ) AND 
         		( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ag_yyyymm ) AND  
         		( "PBWIP"."WIP002"."WBIOCD" = '1' )   
         		using sqlca;
					
		if sqlca.sqlcode <> 0  then
		  	SELECT "PBWIP"."WIP002"."WBBGQT", "PBWIP"."WIP002"."WBBGAT1", "PBWIP"."WIP002"."WBINQT",   
					"PBWIP"."WIP002"."WBINAT1", "PBWIP"."WIP002"."WBINAT3", 
					"PBWIP"."WIP002"."WBUSQT1", "PBWIP"."WIP002"."WBUSAT1",
					"PBWIP"."WIP002"."WBUSQT2","PBWIP"."WIP002"."WBUSAT2",
					"PBWIP"."WIP002"."WBUSQT5","PBWIP"."WIP002"."WBUSAT5",   
					"PBWIP"."WIP002"."WBUSQT7","PBWIP"."WIP002"."WBUSAT7", 
					"PBWIP"."WIP002"."WBUSQT8","PBWIP"."WIP002"."WBUSAT8", 
					"PBWIP"."WIP002"."WBUSQTA","PBWIP"."WIP002"."WBUSATA"  
			 INTO :lc_bgqt, :lc_bgamt, :lc_inqt,:lc_inamt1,:lc_inamt2,
			 		:lc_usqt1,:lc_usamt1,:lc_usqt2,:lc_usamt2,
					:lc_usqt5,:lc_usamt5,:lc_usqt7,:lc_usamt7,
					:lc_usqt8,:lc_usamt8,:lc_usqta,:lc_usamta  
			 	FROM "PBWIP"."WIP002"  
				WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
					( "PBWIP"."WIP002"."WBPLANT" = :ag_plant ) AND  
					( "PBWIP"."WIP002"."WBDVSN" = :ag_dvsn ) AND  
					( "PBWIP"."WIP002"."WBORCT" = :ls_orct ) AND  
					( "PBWIP"."WIP002"."WBITNO" = :ls_itno ) AND  
					( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ag_yyyymm )   using sqlca;

			  UPDATE "PBWIP"."WIP002"  
				  SET "WBBGQT" = WBBGQT  + :lc_bgqt,   
						"WBBGAT1" = WBBGAT1  + :lc_bgamt,   
						"WBINQT" = WBINQT  + :lc_inqt,   
						"WBINAT1" = WBINAT1  + :lc_inamt1,   
						"WBINAT3" = WBINAT3  + :lc_inamt2,   
						"WBUSQT1" = WBUSQT1  + :lc_usqt1,
						"WBUSAT1" = WBUSAT1  + :lc_usamt1,
						"WBUSQT2" = WBUSQT2  + :lc_usqt2, 
						"WBUSAT2" = WBUSAT2  + :lc_usamt2,
						"WBUSQT5" = WBUSQT5  + :lc_usqt5,   
						"WBUSAT5" = WBUSAT5  + :lc_usamt5,   
						"WBUSQT7" = WBUSQT7  + :lc_usqt7,   
						"WBUSAT7" = WBUSAT7  + :lc_usamt7,   
						"WBUSQT8" = WBUSQT8  + :lc_usqt8,   
						"WBUSAT8" = WBUSAT8  + :lc_usamt8,   
						"WBUSQTA" = WBUSQTA  + :lc_usqta,   
						"WBUSATA" = WBUSATA  + :lc_usamta  
				WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
						( "PBWIP"."WIP002"."WBPLANT" = :ag_plant ) AND  
						( "PBWIP"."WIP002"."WBDVSN" = :ag_dvsn ) AND  
						( "PBWIP"."WIP002"."WBORCT" = '9999' ) AND  
						( "PBWIP"."WIP002"."WBITNO" = :ls_itno ) AND  
						( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ag_yyyymm )   
						using sqlca;
			if sqlca.sqlcode <> 0 then
				messagebox("Error", sqlca.sqlerrtext)
			else
				DELETE FROM "PBWIP"."WIP002"  
					WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
						( "PBWIP"."WIP002"."WBPLANT" = :ag_plant ) AND  
						( "PBWIP"."WIP002"."WBDVSN" = :ag_dvsn ) AND  
						( "PBWIP"."WIP002"."WBORCT" = :ls_orct ) AND  
						( "PBWIP"."WIP002"."WBITNO" = :ls_itno ) AND  
						( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ag_yyyymm )   using sqlca;
			end if
		end if
	loop		
close upitem_cur;

return 0
end function

public function integer wf_wip001_orct (string ag_cmcd, string ag_plant, string ag_dvsn);string ls_itno, ls_orct
dec{4} lc_bgqt, lc_inqt, lc_usqt1, lc_usqt2,lc_usqt5,lc_usqt7, lc_usqt8, lc_usqta
dec{0} lc_bgamt, lc_inamt1, lc_inamt2,lc_usamt1, lc_usamt2, lc_usamt5, lc_usamt7, lc_usamt8, lc_usamt9

declare upitem_cur cursor for  
	SELECT "WAITNO","WAORCT" FROM "PBWIP"."WIP001"  
   WHERE ( "PBWIP"."WIP001"."WACMCD" = '01' ) AND  
         ( "PBWIP"."WIP001"."WAPLANT" = :ag_plant ) AND  
         ( "PBWIP"."WIP001"."WADVSN" = :ag_dvsn ) AND   
         ( "PBWIP"."WIP001"."WAIOCD" = '1' )   
         using sqlca;
	
open upitem_cur;	
	do while true
		fetch upitem_cur into :ls_itno,:ls_orct ;
			if sqlca.sqlcode <> 0 then
				exit
			end if
		UPDATE "PBWIP"."WIP001"  
   		SET "WAORCT" = '9999'  
   		WHERE ( "PBWIP"."WIP001"."WACMCD" = '01' ) AND  
         		( "PBWIP"."WIP001"."WAPLANT" = :ag_plant ) AND  
         		( "PBWIP"."WIP001"."WADVSN" = :ag_dvsn ) AND
					( "PBWIP"."WIP001"."WAITNO" = :ls_itno ) AND 
					( "PBWIP"."WIP001"."WAORCT" = :ls_orct ) AND   
         		( "PBWIP"."WIP001"."WAIOCD" = '1' )   
         		using sqlca;
					
		if sqlca.sqlcode <> 0  then
		  	SELECT "PBWIP"."WIP001"."WABGQT", "PBWIP"."WIP001"."WABGAT1", "PBWIP"."WIP001"."WAINQT",   
					"PBWIP"."WIP001"."WAINAT1", "PBWIP"."WIP001"."WAINAT3", 
					"PBWIP"."WIP001"."WAUSQT1", "PBWIP"."WIP001"."WAUSAT1",
					"PBWIP"."WIP001"."WAUSQT2","PBWIP"."WIP001"."WAUSAT2",
					"PBWIP"."WIP001"."WAUSQT5","PBWIP"."WIP001"."WAUSAT5",   
					"PBWIP"."WIP001"."WAUSQT7","PBWIP"."WIP001"."WAUSAT7", 
					"PBWIP"."WIP001"."WAUSQT8","PBWIP"."WIP001"."WAUSAT8", 
					"PBWIP"."WIP001"."WAUSAT9"
			 INTO :lc_bgqt, :lc_bgamt, :lc_inqt,:lc_inamt1,:lc_inamt2,
			 		:lc_usqt1,:lc_usamt1,:lc_usqt2,:lc_usamt2,
					:lc_usqt5,:lc_usamt5,:lc_usqt7,:lc_usamt7,
					:lc_usqt8,:lc_usamt8,:lc_usamt9 
			 	FROM "PBWIP"."WIP001"  
				WHERE ( "PBWIP"."WIP001"."WACMCD" = '01' ) AND  
					( "PBWIP"."WIP001"."WAPLANT" = :ag_plant ) AND  
					( "PBWIP"."WIP001"."WADVSN" = :ag_dvsn ) AND  
					( "PBWIP"."WIP001"."WAORCT" = :ls_orct ) AND  
					( "PBWIP"."WIP001"."WAITNO" = :ls_itno )  
				   using sqlca;

			  UPDATE "PBWIP"."WIP001"  
				  SET "WABGQT" = WABGQT  + :lc_bgqt,   
						"WABGAT1" = WABGAT1  + :lc_bgamt,   
						"WAINQT" = WAINQT  + :lc_inqt,   
						"WAINAT1" = WAINAT1  + :lc_inamt1,   
						"WAINAT3" = WAINAT3  + :lc_inamt2,   
						"WAUSQT1" = WAUSQT1  + :lc_usqt1,
						"WAUSAT1" = WAUSAT1  + :lc_usamt1,
						"WAUSQT2" = WAUSQT2  + :lc_usqt2, 
						"WAUSAT2" = WAUSAT2  + :lc_usamt2,
						"WAUSQT5" = WAUSQT5  + :lc_usqt5,   
						"WAUSAT5" = WAUSAT5  + :lc_usamt5,   
						"WAUSQT7" = WAUSQT7  + :lc_usqt7,   
						"WAUSAT7" = WAUSAT7  + :lc_usamt7,   
						"WAUSQT8" = WAUSQT8  + :lc_usqt8,   
						"WAUSAT8" = WAUSAT8  + :lc_usamt8,   
						"WAUSAT9" = WAUSAT9  + :lc_usamt9 
				WHERE ( "PBWIP"."WIP001"."WACMCD" = '01' ) AND  
						( "PBWIP"."WIP001"."WAPLANT" = :ag_plant ) AND  
						( "PBWIP"."WIP001"."WADVSN" = :ag_dvsn ) AND  
						( "PBWIP"."WIP001"."WAORCT" = '9999' ) AND  
						( "PBWIP"."WIP001"."WAITNO" = :ls_itno )    
						using sqlca;
			if sqlca.sqlcode <> 0 then
				messagebox("Error", "라인에러 : " + ls_itno + " , " + sqlca.sqlerrtext)
			else
				DELETE FROM "PBWIP"."WIP001"  
					WHERE ( "PBWIP"."WIP001"."WACMCD" = '01' ) AND  
						( "PBWIP"."WIP001"."WAPLANT" = :ag_plant ) AND  
						( "PBWIP"."WIP001"."WADVSN" = :ag_dvsn ) AND  
						( "PBWIP"."WIP001"."WAORCT" = :ls_orct ) AND  
						( "PBWIP"."WIP001"."WAITNO" = :ls_itno )   
						using sqlca;
			end if
		end if
	loop		
close upitem_cur;

return 0

end function

public function integer wf_wip001_line (string ag_div);
INSERT INTO "PBWIP"."WIP001"  
     ( "WACMCD","WAPLANT","WADVSN","WAORCT","WAITNO","WAIOCD","WAAVRG1","WAAVRG2",   
       "WABGQT","WABGAT1","WABGAT2","WAINQT","WAINAT1","WAINAT2","WAINAT3","WAINAT4",   
       "WAUSQT1","WAUSAT1","WAUSQT2","WAUSAT2","WAUSQT3","WAUSAT3","WAUSQT4","WAUSAT4",   
       "WAUSQT5","WAUSAT5","WAUSQT6","WAUSAT6","WAUSQT7","WAUSAT7","WAUSQT8","WAUSAT8",   
       "WAUSAT9","WAOHQT","WAOHAT1","WAOHAT2","WASCRP","WARETN","WAPLAN",   
       "WAIPADDR","WAMACADDR","WAINPTDT","WAUPDTDT" )  
SELECT '01',         'D',  "WDIV", "WORCT",  "WITNO",  "WIOCD",   "WAVRG",     0,  
       "WBGQT",  "WBGAT",       0,  "WINQT1", "WINAT1",     0,   "WINAT2",      0,
       "WUSQT1", "WUSAT1","WUSQT3","WUSAT3",         0,        0,         0,       0,
		 "WUSQT2", "WUSAT2",       0,         0,   "WUSQT4", "WUSAT4", "WUSQT5", "WUSAT5",
		        0, "WOHQT", "WOHAT",        0,  "WSCRP",   "WRETN", "WPLAN",     
       :g_s_ipaddr, :g_s_macaddr,"WDATEC"||"WDATEY"||"WDATEM"||"WDATED","WLUDTC"||"WLUDTY"||"WLUDTM"||"WLUDTD"
    
   FROM "DEINVO"."WIPDAV"  
   WHERE "DEINVO"."WIPDAV"."WDIV" = :ag_div  AND
		   "DEINVO"."WIPDAV"."WIOCD" = '1' 
			using sqlca;

if sqlca.sqlcode <> 0 then
	return -1
else
	return 0
end if
end function

public function integer wf_wip001_vndr (string ag_div);INSERT INTO "PBWIP"."WIP001"  
     ( "WACMCD","WAPLANT","WADVSN","WAORCT","WAITNO","WAIOCD","WAAVRG1","WAAVRG2",   
       "WABGQT","WABGAT1","WABGAT2","WAINQT","WAINAT1","WAINAT2","WAINAT3","WAINAT4",   
       "WAUSQT1","WAUSAT1","WAUSQT2","WAUSAT2","WAUSQT3","WAUSAT3","WAUSQT4","WAUSAT4",   
       "WAUSQT5","WAUSAT5","WAUSQT6","WAUSAT6","WAUSQT7","WAUSAT7","WAUSQT8","WAUSAT8",   
       "WAUSAT9","WAOHQT","WAOHAT1","WAOHAT2","WASCRP","WARETN","WAPLAN",   
       "WAIPADDR","WAMACADDR","WAINPTDT","WAUPDTDT" )  
SELECT '01',         'D',  "WDIV", "WORCT",  "WITNO",  "WIOCD",   "WAVRG",     0,  
       "WBGQT",  "WBGAT",       0,  "WINQT1", "WINAT1",     0,   "WINAT2",      0,
       0,             0,  "WUSQT1","WUSAT1",         0,        0,         0,       0,
		 "WUSQT2","WUSAT2", "WUSQT3","WUSAT3",   "WUSQT4", "WUSAT4", "WUSQT5", "WUSAT5",
		        0, "WOHQT", "WOHAT",        0,  "WSCRP",   "WRETN", "WPLAN",     
       :g_s_ipaddr, :g_s_macaddr,"WDATEC"||"WDATEY"||"WDATEM"||"WDATED","WLUDTC"||"WLUDTY"||"WLUDTM"||"WLUDTD"
    
   FROM "DEINVO"."WIPDAV"  
   WHERE "DEINVO"."WIPDAV"."WDIV" = :ag_div  AND
		   "DEINVO"."WIPDAV"."WIOCD" = '2' 
			using sqlca;

if sqlca.sqlcode <> 0 then
	return -1
else
	return 0
end if

end function

on w_wip_backup.create
int iCurrent
call super::create
this.dw_1=create dw_1
this.cb_1=create cb_1
this.cb_2=create cb_2
this.cb_3=create cb_3
this.cb_4=create cb_4
this.cb_5=create cb_5
this.dw_2=create dw_2
this.gb_2=create gb_2
iCurrent=UpperBound(this.Control)
this.Control[iCurrent+1]=this.dw_1
this.Control[iCurrent+2]=this.cb_1
this.Control[iCurrent+3]=this.cb_2
this.Control[iCurrent+4]=this.cb_3
this.Control[iCurrent+5]=this.cb_4
this.Control[iCurrent+6]=this.cb_5
this.Control[iCurrent+7]=this.dw_2
this.Control[iCurrent+8]=this.gb_2
end on

on w_wip_backup.destroy
call super::destroy
destroy(this.dw_1)
destroy(this.cb_1)
destroy(this.cb_2)
destroy(this.cb_3)
destroy(this.cb_4)
destroy(this.cb_5)
destroy(this.dw_2)
destroy(this.gb_2)
end on

event open;call super::open;datawindowchild dwc_01, dwc_02, dwc_03

dw_1.settransobject(sqlca)
dw_2.settransobject(sqlca)

dw_1.getchild("wip001_waplant",dwc_01)
dwc_01.settransobject(sqlca)
dwc_01.retrieve('SLE220')
dw_1.getchild("wip001_wadvsn",dwc_02)
dwc_02.settransobject(sqlca)
dwc_02.retrieve('D')

dw_1.insertrow(0)
end event

type uo_status from w_origin_sheet01`uo_status within w_wip_backup
end type

type dw_1 from datawindow within w_wip_backup
integer x = 69
integer y = 40
integer width = 1326
integer height = 152
integer taborder = 10
boolean bringtotop = true
string title = "none"
string dataobject = "d_wip060i_01"
boolean border = false
boolean livescroll = true
borderstyle borderstyle = stylelowered!
end type

event itemchanged;string ls_colname, ls_plant, ls_null
datawindowchild cdw_1

This.AcceptText()
ls_colname = This.GetColumnName()
IF ls_colname = 'wip001_waplant' Then
   This.SetItem(1,'wip001_wadvsn', ' ')
   ls_plant = This.GetItemString(1,'wip001_waplant')
   This.GetChild("wip001_wadvsn",cdw_1)
   cdw_1.SetTransObject(Sqlca)
   cdw_1.Retrieve(ls_plant)
END IF
end event

type cb_1 from commandbutton within w_wip_backup
integer x = 183
integer y = 400
integer width = 1467
integer height = 112
integer taborder = 30
boolean bringtotop = true
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
string text = "재공밸런스( WIPDAV => WIP001 )"
end type

event clicked;string ls_dvsn, ls_div,ls_plant
long ll_cntx, ll_cntxx, ll_cnty, ll_cntyy, ll_currow

dw_1.accepttext()
setpointer(hourglass!)

ls_dvsn = dw_1.getitemstring(1,"wip001_wadvsn")
ls_plant = dw_1.getitemstring(1,"wip001_waplant")

uo_status.st_message.text = "지역:" + ls_plant + ", 공장:" + ls_dvsn + " : WIPDAV => WIP001 로 데이타 이동중...."

if ls_plant = 'J' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'B'
		case 'S'
			ls_div = 'L'
		case 'H'
			ls_div = 'T'
	end choose
end if

if ls_plant = 'K' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'P'
		case 'S'
			ls_div = 'N'
		case 'H'
			ls_div = 'O'
	end choose
end if

//기존데이타 제거
DELETE FROM "PBWIP"."WIP001"  
   WHERE ( "PBWIP"."WIP001"."WACMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP001"."WAPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP001"."WADVSN" = :ls_dvsn ) using sqlca;
//라인조회수
SELECT count(*)  
   INTO :ll_cntx  
   FROM "DEINVO"."WIPDAV"  
   WHERE "DEINVO"."WIPDAV"."WDIV" = :ls_div AND
			"DEINVO"."WIPDAV"."WIOCD" = '1'
			using sqlca;
//업체조회수			
SELECT count(*)  
   INTO :ll_cntxx  
   FROM "DEINVO"."WIPDAV"  
   WHERE "DEINVO"."WIPDAV"."WDIV" = :ls_div AND
			"DEINVO"."WIPDAV"."WIOCD" = '2'
			using sqlca;
  
if wf_wip001_line(ls_div) = -1 then
	uo_status.st_message.text = "라인데이타 입력시 에러"
	return 0
end if
if wf_wip001_vndr(ls_div) = -1 then
	uo_status.st_message.text = "업체데이타 입력시 에러"
	return 0
end if

//지역 Conversion
UPDATE PBWIP.WIP001
   SET WAPLANT = 'D'
 WHERE WADVSN IN ('A','M','S','H','V') AND
 		 WAPLANT = 'D' 
		 using sqlca;

UPDATE PBWIP.WIP001
   SET WAPLANT = 'J'
 WHERE WADVSN IN ('B','L','T') AND
 		 WAPLANT = 'D'
		 using sqlca;

UPDATE PBWIP.WIP001
   SET WAPLANT = 'K'
 WHERE WADVSN IN ('P','N','O') AND
 		 WAPLANT = 'D' 
		 using sqlca;

//공장 Conversion
UPDATE PBWIP.WIP001   //제동
   SET WADVSN = 'M'
 WHERE WADVSN IN ('B','P') AND
 		 WAPLANT = :ls_plant 
		 using sqlca;

UPDATE PBWIP.WIP001   //조향
   SET WADVSN = 'S'
 WHERE WADVSN IN ('L','N') AND
 		 WAPLANT = :ls_plant
		 using sqlca;

UPDATE PBWIP.WIP001   //공조
   SET WADVSN = 'H'
 WHERE WADVSN IN ('T','O') AND
 		 WAPLANT = :ls_plant 
		 using sqlca;
 
//조코드 업데이트
wf_wip001_orct('01',ls_plant, ls_dvsn)

//라인입력수
SELECT count(*)  
   INTO :ll_cnty  
   FROM "PBWIP"."WIP001"  
   WHERE ( "PBWIP"."WIP001"."WACMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP001"."WAPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP001"."WADVSN" = :ls_dvsn ) AND
			( "PBWIP"."WIP001"."WAIOCD" = '1' )
			using sqlca;
//업체입력수			
SELECT count(*)  
   INTO :ll_cntyy  
   FROM "PBWIP"."WIP001"  
   WHERE ( "PBWIP"."WIP001"."WACMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP001"."WAPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP001"."WADVSN" = :ls_dvsn ) AND
			( "PBWIP"."WIP001"."WAIOCD" = '2' )
			using sqlca;
			
ll_currow = dw_2.insertrow(0)
dw_2.setitem(ll_currow,"plant",ls_plant)
dw_2.setitem(ll_currow,"dvsn",ls_dvsn)
dw_2.setitem(ll_currow,"wipdb",'wip001')
dw_2.setitem(ll_currow,"ydate",' ')
dw_2.setitem(ll_currow,"iocd",'라인')
dw_2.setitem(ll_currow,"tot_sel",ll_cntx)
dw_2.setitem(ll_currow,"tot_up",ll_cnty)
ll_currow = dw_2.insertrow(0)
dw_2.setitem(ll_currow,"plant",ls_plant)
dw_2.setitem(ll_currow,"dvsn",ls_dvsn)
dw_2.setitem(ll_currow,"wipdb",'wip001')
dw_2.setitem(ll_currow,"ydate",' ')
dw_2.setitem(ll_currow,"iocd",'업체')
dw_2.setitem(ll_currow,"tot_sel",ll_cntxx)
dw_2.setitem(ll_currow,"tot_up",ll_cntyy)

			


end event

type cb_2 from commandbutton within w_wip_backup
integer x = 183
integer y = 1184
integer width = 1467
integer height = 112
integer taborder = 40
boolean bringtotop = true
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
string text = "재공트랜스( WIPTAX => WIP004 )"
end type

event clicked;string ls_dvsn, ls_div,ls_plant, ls_date
long ll_cntx, ll_cnty

setpointer(hourglass!)
dw_1.accepttext()
ls_dvsn = dw_1.getitemstring(1,"wip001_wadvsn")
ls_plant = dw_1.getitemstring(1,"wip001_waplant")
ls_date = dw_1.getitemstring(1,"wip001_wainptdt")

if ls_plant = 'J' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'B'
		case 'S'
			ls_div = 'L'
		case 'H'
			ls_div = 'T'
	end choose
end if

if ls_plant = 'K' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'P'
		case 'S'
			ls_div = 'N'
		case 'H'
			ls_div = 'O'
	end choose
end if

SELECT count(*)  
   INTO :ll_cntx  
   FROM "DEINVO"."WIPTAX"  
   WHERE "WTDIV" = :ls_div AND
			"WTDTCC"||"WTDTYY"||"WTDTMM" = :ls_date   USING SQLCA;
			
//데이타 삭제
DELETE FROM "PBWIP"."WIP004"
	WHERE ( "PBWIP"."WIP004"."WDCMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP004"."WDPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP004"."WDDVSN" = :ls_dvsn ) AND
			( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) using sqlca;

//데이타 마이그레이션
INSERT INTO "PBWIP"."WIP004"  
       ( "WDCMCD","WDSLTY","WDSRNO","WDPLANT","WDDVSN","WDIOCD","WDITNO","WDRVNO","WDDESC","WDSPEC",   
         "WDUNIT","WDITCL","WDSRCE","WDUSGE","WDPDCD","WDSLNO","WDPRSRTY","WDPRSRNO","WDPRSRNO1",   
         "WDPRSRNO2","WDPRNO","WDPRDPT","WDCHDPT","WDDATE","WDPRQT","WDCHQT","WDIPADDR","WDMACADDR",   
         "WDINPTID","WDUPDTID","WDINPTDT","WDINPTTM","WDUPDTDT" )  
	SELECT '01',SUBSTR("WTSRNO",1,2),SUBSTR("WTSRNO",3,8),'D',"WTDIV","WTIOCD","WTITNO","WTRVNO","WTDESC","WTSPEC",
			"WTUM","WTCLSS","WTSRCD","WTUSGE","WTPDCD","WTSLNO",SUBSTR("WTPRSR",1,2),SUBSTR("WTPRSR",3,8),' ',   
     		' ',"WTPRNO","WTPDPT","WTCDPT","WTDTCC"||"WTDTYY"||"WTDTMM"||"WTDTDD","WTQTY1","WTQTY2",' ',' ',   
         ' ',' ',' ', ' ', ' '  
   FROM "DEINVO"."WIPTAX"  
   WHERE "WTDIV" = :ls_div AND
			"WTDTCC"||"WTDTYY"||"WTDTMM" = :ls_date   USING SQLCA;
			
IF Sqlca.SqlCode <> 0 THEN
	MessageBox("DataBase Error", sqlca.sqlerrtext)
	RETURN 0
END IF

//지역 Conversion
UPDATE PBWIP.WIP004
   SET WDPLANT = 'D'
 WHERE WDDVSN IN ('A','M','S','H','V') AND
 		 WDPLANT = 'D' AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) 
		 using sqlca;

UPDATE PBWIP.WIP004
   SET WDPLANT = 'J'
 WHERE WDDVSN IN ('B','L','T') AND
       WDPLANT = 'D' AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) 
		 using sqlca;

UPDATE PBWIP.WIP004
   SET WDPLANT = 'K'
 WHERE WDDVSN IN ('P','N','O') AND
 		 WDPLANT = 'D' AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date )
		 using sqlca;

//공장 Conversion
UPDATE PBWIP.WIP004   //제동
   SET WDDVSN = 'M'
 WHERE WDDVSN IN ('B','P') AND
 		 WDPLANT = :ls_plant AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date )
		 using sqlca;

UPDATE PBWIP.WIP004   //조향
   SET WDDVSN = 'S'
 WHERE WDDVSN IN ('L','N') AND
       WDPLANT = :ls_plant AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date )
		 using sqlca;

UPDATE PBWIP.WIP004   //공조
   SET WDDVSN = 'H'
 WHERE WDDVSN IN ('T','O') AND
       WDPLANT = :ls_plant AND
 		 ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date )
		 using sqlca;

UPDATE "PBWIP"."WIP004"  
   SET "WDCHDPT" = '9999'  
   WHERE ( "PBWIP"."WIP004"."WDCMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP004"."WDPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP004"."WDDVSN" = :ls_dvsn ) AND  
         ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) AND  
         ( "PBWIP"."WIP004"."WDIOCD" = '1' )   
         using sqlca;

SELECT count(*)  
   INTO :ll_cnty  
   FROM "PBWIP"."WIP004"  
   WHERE ( "PBWIP"."WIP004"."WDCMCD" = :g_s_company ) AND  
         ( "PBWIP"."WIP004"."WDPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP004"."WDDVSN" = :ls_dvsn ) AND
			( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) using sqlca;
			
uo_status.st_message.text = "조회수 : " + string(ll_cntx) + ", Insert수 : " + string(ll_cnty)

end event

type cb_3 from commandbutton within w_wip_backup
integer x = 183
integer y = 656
integer width = 1467
integer height = 112
integer taborder = 50
boolean bringtotop = true
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
string text = "재공이월DB( WIPDAW => WIP002 )"
end type

event clicked;string ls_dvsn, ls_div,ls_plant, ls_date, ls_yyyy, ls_mm
long ll_cntx, ll_cntxx, ll_cnty, ll_cntyy, ll_cnt

setpointer(hourglass!)
dw_1.accepttext()
ls_dvsn = dw_1.getitemstring(1,"wip001_wadvsn")
ls_plant = dw_1.getitemstring(1,"wip001_waplant")
ls_date = '199901'

if ls_plant = 'J' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'B'
		case 'S'
			ls_div = 'L'
		case 'H'
			ls_div = 'T'
	end choose
end if

if ls_plant = 'K' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'P'
		case 'S'
			ls_div = 'N'
		case 'H'
			ls_div = 'O'
	end choose
end if

DO WHILE (ls_date <= '200212')
	uo_status.st_message.text = ls_date + "," + "지역:" + ls_plant + ", 공장:" + ls_dvsn + " : WIPDAW => WIP002 로 데이타 이동중...."
	ls_yyyy = mid(ls_date,1,4)
	ls_mm = mid(ls_date,5)
	//데이타 삭제
	DELETE FROM "PBWIP"."WIP002"
		WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
				( "PBWIP"."WIP002"."WBPLANT" = :ls_plant ) AND  
				( "PBWIP"."WIP002"."WBDVSN" = :ls_dvsn ) AND  
				( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ls_date )  
				using sqlca;
		
	//데이타 인서트(wipdaw -> wip002)
	choose case ls_mm
		case '01'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW"  
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND 
						( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )
							using sqlca;
			SELECT count(*)  
				INTO :ll_cntxx  
				FROM "DEINVO"."WIPDAW"  
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND 
						( "DEINVO"."WIPDAW"."WCIOCD" = '2' ) AND
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )
							using sqlca;
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '02'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND 
						( "DEINVO"."WIPDAW"."WCIOCD" = '1' ) AND
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '03'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy ) AND
						NOT("WCBQT3" = 0 AND "WCBAT3" = 0  AND "WCINQTA3" = 0 AND "WCUSQTA3" = 0 AND "WCUSQTB3" = 0
							AND "WCUSQTC3" = 0 AND "WCUSQTD3" = 0 AND "WCUSQTE3" = 0 AND "WCUSQTF3" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if		
		case '04'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT4" = 0 AND "WCBAT4" = 0  AND "WCINQTA4" = 0 AND "WCUSQTA4" = 0 AND "WCUSQTB4" = 0
							AND "WCUSQTC4" = 0 AND "WCUSQTD4" = 0 AND "WCUSQTE4" = 0 AND "WCUSQTF4" = 0) 
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '05'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy ) AND
						NOT("WCBQT5" = 0 AND "WCBAT5" = 0  AND "WCINQTA5" = 0 AND "WCUSQTA5" = 0 AND "WCUSQTB5" = 0
							AND "WCUSQTC5" = 0 AND "WCUSQTD5" = 0 AND "WCUSQTE5" = 0 AND "WCUSQTF5" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '06'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT6" = 0 AND "WCBAT6" = 0  AND "WCINQTA6" = 0 AND "WCUSQTA6" = 0 AND "WCUSQTB6" = 0
							AND "WCUSQTC6" = 0 AND "WCUSQTD6" = 0 AND "WCUSQTE6" = 0 AND "WCUSQTF6" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '07'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT7" = 0 AND "WCBAT7" = 0  AND "WCINQTA7" = 0 AND "WCUSQTA7" = 0 AND "WCUSQTB7" = 0
							AND "WCUSQTC7" = 0 AND "WCUSQTD7" = 0 AND "WCUSQTE7" = 0 AND "WCUSQTF7" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '08'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT8" = 0 AND "WCBAT8" = 0  AND "WCINQTA8" = 0 AND "WCUSQTA8" = 0 AND "WCUSQTB8" = 0
							AND "WCUSQTC8" = 0 AND "WCUSQTD8" = 0 AND "WCUSQTE8" = 0 AND "WCUSQTF8" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '09'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy ) AND
						NOT("WCBQT9" = 0 AND "WCBAT9" = 0  AND "WCINQTA9" = 0 AND "WCUSQTA9" = 0 AND "WCUSQTB9" = 0
							AND "WCUSQTC9" = 0 AND "WCUSQTD9" = 0 AND "WCUSQTE9" = 0 AND "WCUSQTF9" = 0)   
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '10'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT10" = 0 AND "WCBAT10" = 0  AND "WCINQTA10" = 0 AND "WCUSQTA10" = 0 AND "WCUSQTB10" = 0
							AND "WCUSQTC10" = 0 AND "WCUSQTD10" = 0 AND "WCUSQTE10" = 0 AND "WCUSQTF10" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '11'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy )  AND
						NOT("WCBQT11" = 0 AND "WCBAT11" = 0  AND "WCINQTA11" = 0 AND "WCUSQTA11" = 0 AND "WCUSQTB11" = 0
							AND "WCUSQTC11" = 0 AND "WCUSQTD11" = 0 AND "WCUSQTE11" = 0 AND "WCUSQTF11" = 0)  
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
		case '12'
			//데이타 마이그레이션 총수(wipdaw)
			SELECT count(*)  
				INTO :ll_cntx  
				FROM "DEINVO"."WIPDAW" 
				WHERE ( "DEINVO"."WIPDAW"."WCDIV" = :ls_div ) AND  
						( "DEINVO"."WIPDAW"."WCYEARC"||"DEINVO"."WIPDAW"."WCYEARY" = :ls_yyyy ) AND
						NOT("WCBQT12" = 0 AND "WCBAT12" = 0  AND "WCINQTA12" = 0 AND "WCUSQTA12" = 0 AND "WCUSQTB12" = 0
							AND "WCUSQTC12" = 0 AND "WCUSQTD12" = 0 AND "WCUSQTE12" = 0 AND "WCUSQTF12" = 0)   
				using sqlca;
				
			if wf_wip002_line(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "line insert error"
				return 0
			end if
			if wf_wip002_vndr(ls_div,ls_yyyy,ls_mm) = -1 then
				uo_status.st_message.text = "vndr insert error"
				return 0
			end if
	end choose
				
	IF Sqlca.SqlCode <> 0 THEN
		MessageBox("DataBase Error", sqlca.sqlerrtext)
		RETURN 0
	END IF
	
	//지역 Conversion
	UPDATE PBWIP.WIP002
		SET WBPLANT = 'D'
	 WHERE WBDVSN IN ('A','M','S','H','V') AND
			 WBPLANT = 'D' AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	UPDATE PBWIP.WIP002
		SET WBPLANT = 'J'
	 WHERE WBDVSN IN ('B','L','T') AND
			 WBPLANT = 'D' AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	UPDATE PBWIP.WIP002
		SET WBPLANT = 'K'
	 WHERE WBDVSN IN ('P','N','O') AND
			 WBPLANT = 'D' AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	//공장 Conversion
	UPDATE PBWIP.WIP002   //제동
		SET WBDVSN = 'M'
	 WHERE WBDVSN IN ('B','P') AND
			 WBPLANT = :ls_plant AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	UPDATE PBWIP.WIP002   //조향
		SET WBDVSN = 'S'
	 WHERE WBDVSN IN ('L','N') AND
			 WBPLANT = :ls_plant AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	UPDATE PBWIP.WIP002   //공조
		SET WBDVSN = 'H'
	 WHERE WBDVSN IN ('T','O') AND
			 WBPLANT = :ls_plant AND
			 WBYEAR||WBMONTH = :ls_date  
			 using sqlca;
	
	//조코드 업데이트
	wf_update_orct('01', ls_plant, ls_dvsn, ls_date)
	
	//인서트된 총수 
	SELECT count(*)  
		INTO :ll_cnty  
		FROM "PBWIP"."WIP002"
		WHERE ( "PBWIP"."WIP002"."WBCMCD" = '01' ) AND  
				( "PBWIP"."WIP002"."WBPLANT" = :ls_plant ) AND  
				( "PBWIP"."WIP002"."WBDVSN" = :ls_dvsn ) AND  
				( "PBWIP"."WIP002"."WBYEAR"||"PBWIP"."WIP002"."WBMONTH" = :ls_date )  
				using sqlca;
	//년월 증가
	uf_wip_addmonth(ls_date,1)
LOOP


end event

type cb_4 from commandbutton within w_wip_backup
integer x = 183
integer y = 920
integer width = 1467
integer height = 112
integer taborder = 60
boolean bringtotop = true
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
string text = "재공창고DB( WIPT42 => WIP003 )"
end type

event clicked;string ls_dvsn, ls_div,ls_plant, ls_date, ls_yyyy, ls_mm
long ll_cntx, ll_cnty

setpointer(hourglass!)
dw_1.accepttext()
ls_dvsn = dw_1.getitemstring(1,"wip001_wadvsn")
ls_plant = dw_1.getitemstring(1,"wip001_waplant")
ls_date = dw_1.getitemstring(1,"wip001_wainptdt")
ls_yyyy = mid(ls_date,1,4)
ls_mm = mid(ls_date,5)

if ls_plant = 'J' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'B'
		case 'S'
			ls_div = 'L'
		case 'H'
			ls_div = 'T'
	end choose
end if

if ls_plant = 'K' then
	choose case ls_dvsn
		case 'M'
			ls_div = 'P'
		case 'S'
			ls_div = 'N'
		case 'H'
			ls_div = 'O'
	end choose
end if

SELECT count(*)  
    INTO :ll_cntx  
    FROM "DEINVO"."WIPT42"  
   WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         ( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
			using sqlca;


//데이타 삭제
DELETE FROM "PBWIP"."WIP003"
	WHERE ( "PBWIP"."WIP003"."WCCMCD" = '01' ) AND  
         ( "PBWIP"."WIP003"."WCPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP003"."WCDVSN" = :ls_dvsn ) AND  
         ( "PBWIP"."WIP003"."WCYEAR"||"PBWIP"."WIP003"."WCMONTH" = :ls_date )  
         using sqlca;
	
//데이타 인서트(wipdaw -> wip003)
choose case ls_mm
	case '01'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )  
  		  SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG1",      0, "WOBGAT1",     0,        0, "WOINAT1",    0,
         	    0,  "WOUSAT1A",   0,    "WOUSAT1C",    0,         0,      0,        0,
         	    0,  "WOUSAT1B",   0,          0,        0,       0,    "WOUSAT1D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '02'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG2",      0, "WOBGAT2",     0,        0, "WOINAT2",    0,
         	    0,  "WOUSAT2A",   0,    "WOUSAT2C",    0,         0,      0,        0,
         	    0,  "WOUSAT2B",   0,          0,        0,       0,    "WOUSAT2D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '03'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG3",      0, "WOBGAT3",     0,        0, "WOINAT3",    0,
         	    0,  "WOUSAT3A",   0,    "WOUSAT3C",    0,         0,      0,        0,
         	    0,  "WOUSAT3B",   0,          0,        0,       0,    "WOUSAT3D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '04'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG4",      0, "WOBGAT4",     0,        0, "WOINAT4",    0,
         	    0,  "WOUSAT4A",   0,    "WOUSAT4C",    0,         0,      0,        0,
         	    0,  "WOUSAT4B",   0,          0,        0,       0,    "WOUSAT4D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '05'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG5",      0, "WOBGAT5",     0,        0, "WOINAT5",    0,
         	    0,  "WOUSAT5A",   0,    "WOUSAT5C",    0,         0,      0,        0,
         	    0,  "WOUSAT5B",   0,          0,        0,       0,    "WOUSAT5D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '06'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG6",      0, "WOBGAT6",     0,        0, "WOINAT6",    0,
         	    0,  "WOUSAT6A",   0,    "WOUSAT6C",    0,         0,      0,        0,
         	    0,  "WOUSAT6B",   0,          0,        0,       0,    "WOUSAT6D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '07'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG7",      0, "WOBGAT7",     0,        0, "WOINAT7",    0,
         	    0,  "WOUSAT7A",   0,    "WOUSAT7C",    0,         0,      0,        0,
         	    0,  "WOUSAT7B",   0,          0,        0,       0,    "WOUSAT7D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '08'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG8",      0, "WOBGAT8",     0,        0, "WOINAT8",    0,
         	    0,  "WOUSAT8A",   0,    "WOUSAT8C",    0,         0,      0,        0,
         	    0,  "WOUSAT8B",   0,          0,        0,       0,    "WOUSAT8D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '09'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRG9",      0, "WOBGAT9",     0,        0, "WOINAT9",    0,
         	    0,  "WOUSAT9A",   0,    "WOUSAT9C",    0,         0,      0,        0,
         	    0,  "WOUSAT9B",   0,          0,        0,       0,    "WOUSAT9D",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '10'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRGA",      0, "WOBGATA",     0,        0, "WOINATA",    0,
         	    0,  "WOUSATAA",   0,    "WOUSATAC",    0,         0,      0,        0,
         	    0,  "WOUSATAB",   0,          0,        0,       0,    "WOUSATAD",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '11'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRGB",      0, "WOBGATB",     0,        0, "WOINATB",    0,
         	    0,  "WOUSATBA",   0,    "WOUSATBC",    0,         0,      0,        0,
         	    0,  "WOUSATBB",   0,          0,        0,       0,    "WOUSATBD",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
	case '12'
		INSERT INTO "PBWIP"."WIP003"  
         ( "WCCMCD","WCPLANT","WCDVSN","WCITNO","WCYEAR","WCMONTH","WCITCL","WCSRCE","WCPDCD",   
           "WCAVRG1","WCAVRG2","WCBGAT1","WCBGAT2","WCINQT","WCINAT1","WCINAT2",   
           "WCUSQT1","WCUSAT1","WCUSQT2","WCUSAT2","WCUSQT3","WCUSAT3","WCUSQT4","WCUSAT4",   
           "WCUSQT5","WCUSAT5","WCUSQT6","WCUSAT6","WCUSAT7","WCUSQT8","WCUSAT8","WCUSAT9",   
           "WCIPADDR","WCMACADDR","WCINPTDT","WCUPDTDT" )
		SELECT '01', 'D', "WODIV","WOITNO","WOYEARC"||"WOYEARY",:ls_mm ,"WOITCL","WOSRCE",' ',   
         	"WOAVRGC",      0, "WOBGATC",     0,        0, "WOINATC",    0,
         	    0,  "WOUSATCA",   0,    "WOUSATCC",    0,         0,      0,        0,
         	    0,  "WOUSATCB",   0,          0,        0,       0,    "WOUSATCD",  0,
           ' ', ' ', ' ', ' '
    		FROM "DEINVO"."WIPT42"  
   		WHERE ( "DEINVO"."WIPT42"."WODIV" = :ls_div ) AND  
         		( "DEINVO"."WIPT42"."WOYEARC"||"DEINVO"."WIPT42"."WOYEARY" = :ls_yyyy )   
					using sqlca;
end choose
			
IF Sqlca.SqlCode <> 0 THEN
	MessageBox("DataBase Error", sqlca.sqlerrtext)
	RETURN 0
END IF

//지역 Conversion
UPDATE PBWIP.WIP003
   SET WCPLANT = 'D'
 WHERE WCDVSN IN ('A','M','S','H','V') AND
 		 WCPLANT = 'D' AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

UPDATE PBWIP.WIP003
   SET WCPLANT = 'J'
 WHERE WCDVSN IN ('B','L','T') AND
 		 WCPLANT = 'D' AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

UPDATE PBWIP.WIP003
   SET WCPLANT = 'K'
 WHERE WCDVSN IN ('P','N','O') AND
 		 WCPLANT = 'D' AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

//공장 Conversion
UPDATE PBWIP.WIP003   //제동
   SET WCDVSN = 'M'
 WHERE WCDVSN IN ('B','P') AND
 		 WCPLANT = :ls_plant AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

UPDATE PBWIP.WIP003   //조향
   SET WCDVSN = 'S'
 WHERE WCDVSN IN ('L','N') AND
 		 WCPLANT = :ls_plant AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

UPDATE PBWIP.WIP003   //공조
   SET WCDVSN = 'H'
 WHERE WCDVSN IN ('T','O') AND
 		 WCPLANT = :ls_plant AND
 		 WCYEAR||WCMONTH = :ls_date  
		 using sqlca;

//조코드 업데이트


//인서트된 총수 
SELECT count(*)  
   INTO :ll_cnty  
   FROM "PBWIP"."WIP003"
   WHERE ( "PBWIP"."WIP003"."WCCMCD" = '01' ) AND  
         ( "PBWIP"."WIP003"."WCPLANT" = :ls_plant ) AND  
         ( "PBWIP"."WIP003"."WCDVSN" = :ls_dvsn ) AND  
         ( "PBWIP"."WIP003"."WCYEAR"||"PBWIP"."WIP003"."WCMONTH" = :ls_date )  
         using sqlca;
			
uo_status.st_message.text = "조회수 : " + string(ll_cntx) + ", Insert수 : " + string(ll_cnty)

end event

type cb_5 from commandbutton within w_wip_backup
integer x = 183
integer y = 1428
integer width = 1467
integer height = 112
integer taborder = 70
boolean bringtotop = true
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
boolean enabled = false
string text = "재공트랜스(사용용도설정)"
end type

event clicked;string ls_slty, ls_srno, ls_plant, ls_dvsn, ls_date
string ls_itno, ls_cls, ls_srce, ls_rtngub, ls_xuse, ls_vsrno
long ll_cntx, ll_cnty

setpointer(hourglass!)
dw_1.accepttext()
ls_dvsn = dw_1.getitemstring(1,"wip001_wadvsn")
ls_plant = dw_1.getitemstring(1,"wip001_waplant")
ls_date = dw_1.getitemstring(1,"wip001_wainptdt")

DECLARE invqty_cur CURSOR FOR  
  SELECT DISTINCT "PBINV"."INV401"."SLIPTYPE",
  						"PBINV"."INV401"."SRNO",
         			"PBINV"."INV401"."ITNO",   
         			"PBINV"."INV401"."CLS",   
         			"PBINV"."INV401"."SRCE",   
         			"PBINV"."INV401"."RTNGUB",   
         			"PBINV"."INV401"."XUSE",   
         			"PBINV"."INV401"."VSRNO"  
   FROM "PBWIP"."WIP004",   
        "PBINV"."INV401"  
   WHERE ( "PBWIP"."WIP004"."WDCMCD" = "PBINV"."INV401"."COMLTD" ) and  
         ( "PBWIP"."WIP004"."WDPRSRTY" = "PBINV"."INV401"."SLIPTYPE" ) and  
         ( "PBWIP"."WIP004"."WDPRSRNO" = "PBINV"."INV401"."SRNO" ) and  
         ( "PBINV"."INV401"."TDTE4" = "PBWIP"."WIP004"."WDDATE" ) and  
         ( ( "PBWIP"."WIP004"."WDCMCD" = '01' ) AND 
			  ( "PBWIP"."WIP004"."WDDVSN" = :ls_dvsn ) AND
			  ( "PBWIP"."WIP004"."WDPLANT" = :ls_plant ) AND
			  NOT ( "PBWIP"."WIP004"."WDPRSRTY" IN ('SM','RM')) AND
         ( {fn substring("PBWIP"."WIP004"."WDDATE",1,6)} = :ls_date ) )   
			USING SQLCA;
OPEN invqty_cur;
	do while true
		FETCH invqty_cur INTO :ls_slty,:ls_srno,:ls_itno,:ls_cls,:ls_srce,:ls_rtngub,:ls_xuse,:ls_vsrno ;
			if sqlca.sqlcode <> 0 then
				exit
			end if
			
		CHOOSE CASE ls_slty
			CASE 'IS','IP'
				choose case ls_xuse
					case '01','02'
						
					case '03','05'
						
					case '04'
						
					case '07'
				
				end choose
			CASE 'IE'
				
			CASE 'RS'
				
			CASE 'RP'
				
				
		END CHOOSE
	loop
CLOSE invqty_cur;


end event

type dw_2 from datawindow within w_wip_backup
integer x = 1815
integer y = 264
integer width = 2606
integer height = 1508
integer taborder = 30
boolean bringtotop = true
string title = "none"
string dataobject = "d_wip060i_02"
boolean livescroll = true
borderstyle borderstyle = stylelowered!
end type

type gb_2 from groupbox within w_wip_backup
integer x = 69
integer y = 232
integer width = 1723
integer height = 1544
integer taborder = 20
integer textsize = -12
integer weight = 700
fontcharset fontcharset = hangeul!
fontpitch fontpitch = fixed!
fontfamily fontfamily = modern!
string facename = "굴림체"
long textcolor = 33554432
long backcolor = 67108864
string text = "재공"
end type

