ALTER TABLE dbo.TH_INF_DATA ALTER COLUMN CYCLE_TIME NUMERIC (12,1) ;
GO

ALTER TABLE dbo.TM_MODEL_CYCLE ALTER COLUMN CYCLE_TIME NUMERIC (12,1) ;
GO

CREATE TABLE [dbo].[TH_DATA_TIME_BK](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[MODEL] [varchar](10) NOT NULL DEFAULT '',
	[TIME_ZONE] [varchar](11) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
	[PROD_SHIFT] [varchar](1) NULL,
	[SEQ] [int] NULL ) ON [PRIMARY]

INSERT INTO [TH_DATA_TIME_BK]
SELECT [PROD_YMD]
      ,[MODEL]
      ,[TIME_ZONE]
      ,[WORK_QTY]
      ,[WORK_RATE]
      ,[PROD_SHIFT]
      ,[SEQ]
  FROM [ORMS].[dbo].[TH_DATA_TIME]

GO

DELETE TABLE [dbo].[TH_DATA_TIME]

GO

CREATE TABLE [dbo].[TH_DATA_TIME](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[MODEL] [varchar](10) NOT NULL DEFAULT '',
	[TIME_ZONE] [varchar](11) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
	[PROD_SHIFT] [varchar](1) NULL,
	[SEQ] [int] NULL,
 CONSTRAINT [PK_TH_DATA_TIME] PRIMARY KEY CLUSTERED 
 (
	[PROD_YMD], [MODEL], [TIME_ZONE]
 )ON [PRIMARY] ) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TH_DATA_DAY_BK](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[PROD_SHIFT] [varchar](1) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL ) ON [PRIMARY]

GO

INSERT INTO [TH_DATA_DAY_BK]
SELECT [PROD_YMD]
      ,[PROD_SHIFT]
      ,[WORK_QTY]
      ,[WORK_RATE]
  FROM [ORMS].[dbo].[TH_DATA_DAY]
GO

DELETE TABLE [dbo].[TH_DATA_DAY]
GO

CREATE TABLE [dbo].[TH_DATA_DAY](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[PROD_SHIFT] [varchar](1) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
 CONSTRAINT [PK_TH_DATA_DAY] PRIMARY KEY CLUSTERED 
(
	[PROD_YMD], [PROD_SHIFT]
) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TH_DATA_MODEL_BK](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[MODEL] [varchar](10) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
	[PLAN_QTY] [int] NULL) ON [PRIMARY]

GO

INSERT INTO [TH_DATA_MODEL_BK]
SELECT [PROD_YMD]
      ,[MODEL]
      ,[WORK_QTY]
      ,[WORK_RATE]
      ,[PLAN_QTY]
  FROM [ORMS].[dbo].[TH_DATA_MODEL]
GO

DROP TABLE [TH_DATA_MODEL]
GO

CREATE TABLE [dbo].[TH_DATA_MODEL](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[MODEL] [varchar](10) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
	[PLAN_QTY] [int] NULL,
 CONSTRAINT [PK_TH_DATA_MODEL] PRIMARY KEY CLUSTERED 
(
	[PROD_YMD], [MODEL]
) ON [PRIMARY]
) ON [PRIMARY]

GO