-- BOM113 MIGRATION
INSERT INTO PBPDM.BOM113
( ZCMCD,ZDATE,ZPLANT,ZDIV,ZMDCD,ZMDNO,ZSERIAL,ZLEVEL,ZPITNO,ZITNO,ZREV,ZDESC,ZSPEC,ZUNIT1,ZUNITQTY,
ZCVTFACT,ZUNIT2,ZSRCE,ZABCCODE,ZISSCODE,ZWHLCODE,ZLOTSIZE,ZLEADTIME,ZMOVCOST,ZRCPCOST,ZOUTCOST,ZWKCT,
ZGRAD,ZALTNO,ZFMDT,ZTODT,ZCALC,ZEXPLANT,ZEXDIV,ZCOMCD,ZYGCHK,ZYGCST,ZDAMDANG,
ZPRUNT,ZPTOD,ZPCURR,ZPTOTDAN,ZPRUTC,ZPVSRNO,ZPVEND,ZSCMOVCOST,ZSCRCPCOST,ZSCOUTCOST )

SELECT ZCMCD,ZDATE,ZPLANT,ZDIV,ZMDCD,ZMDNO,ZSERIAL,ZLEVEL,ZPITNO,ZITNO,ZREV,ZDESC,ZSPEC,ZUNIT1,ZUNITQTY,
ZCVTFACT,ZUNIT2,ZSRCE,ZABCCODE,ZISSCODE,ZWHLCODE,ZLOTSIZE,ZLEADTIME,ZMOVCOST,ZRCPCOST,ZOUTCOST,ZWKCT,
ZGRAD,ZALTNO,ZFMDT,ZTODT,ZCALC,'','',ZCOMCD,ZYGCHK,ZYGCST,ZDAMDANG,
ZPRUNT,ZPTOD,ZPCURR,ZPTOTDAN,ZPRUTC,ZPVSRNO,ZPVEND,0,0,0
FROM PBPDM.BOMT13;

-- BOM115 MIGRATION
INSERT INTO PBPDM.BOM115
( ZCMCD,ZDATE,ZPLANT,ZDIV,ZMDCD,ZMDNO,ZSERIAL,ZLEVEL,ZPITNO,ZITNO,ZREV,ZDESC,ZSPEC,ZUNIT1,ZUNITQTY,
ZCVTFACT,ZUNIT2,ZSRCE,ZABCCODE,ZISSCODE,ZWHLCODE,ZLOTSIZE,ZLEADTIME,ZMOVCOST,ZRCPCOST,ZOUTCOST,ZWKCT,
ZGRAD,ZALTNO,ZFMDT,ZTODT,ZCALC,ZEXPLANT,ZEXDIV,ZCOMCD,ZYGCHK,ZYGCST,ZSCMOVCOST,ZSCRCPCOST,ZSCOUTCOST )

SELECT ZCMCD,ZDATE,ZPLANT,ZDIV,ZMDCD,ZMDNO,ZSERIAL,ZLEVEL,ZPITNO,ZITNO,ZREV,ZDESC,ZSPEC,ZUNIT1,ZUNITQTY,
ZCVTFACT,ZUNIT2,ZSRCE,ZABCCODE,ZISSCODE,ZWHLCODE,ZLOTSIZE,ZLEADTIME,ZMOVCOST,ZRCPCOST,ZOUTCOST,ZWKCT,
ZGRAD,ZALTNO,ZFMDT,ZTODT,ZCALC,ZEXPLANT,ZEXDIV,ZCOMCD,ZYGCHK,ZYGCST,0,0,0
FROM PBPDM.BOMT15