SELECT * FROM [IPISELE_SVR\IPIS].CMMS.DBO.EQUIP_MASTER
WHERE EQUIP_CODE LIKE 'AEL%' OR EQUIP_CODE LIKE 'AMS%'

UNION ALL

SELECT * FROM [IPISMAC_SVR\IPIS].CMMS.DBO.EQUIP_MASTER
WHERE EQUIP_CODE LIKE 'MML%' OR EQUIP_CODE LIKE 'SML%'

UNION ALL

SELECT * FROM [IPISHVAC_SVR\IPIS].CMMS.DBO.EQUIP_MASTER
WHERE EQUIP_CODE LIKE 'VNV%' OR EQUIP_CODE LIKE 'VHL%' OR
EQUIP_CODE = 'VRD010'