SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



ALTER    TRIGGER [TRIGGER_UPLOAD1] ON [dbo].[equip_master] 
FOR INSERT

AS
DECLARE @AAA DATETIME
SELECT @AAA = GETDATE()

--IF EXISTS(
--SELECT B.AREA_CODE, B.FACTORY_CODE, B.EQUIP_CODE, B.EQUIP_NAME, B.ASSET_CODE, B.EQUIP_DIV_CODE, B.EQUIP_SPEC, B.EQUIP_USE, B.CC_CODE, B.LINE_CODE, B.EQUIP_SHORT_NAME, B.EQUIP_INSTALL_DATE, B.EQUIP_PROCESS_NUMBER, B.DEPT_CODE_OP, B.DEPT_CODE_USE, B.COMP_CODE_VENDER, B.COMP_CODE_AGENT, @AAA
--FROM EQUIP_MASTER_UPLOAD A, INSERTED B
--WHERE (A.AREA_CODE = B.AREA_CODE) AND A.FACTORY_CODE=B.FACTORY_CODE AND  A.EQUIP_CODE=B.EQUIP_CODE AND A.UP_DIV='Y')
--	BEGIN
--		INSERT INTO EQUIP_MASTER_UPLOAD(AREA_CODE, FACTORY_CODE, EQUIP_CODE, EQUIP_NAME, ASSET_CODE, EQUIP_DIV_CODE, EQUIP_SPEC, EQUIP_USE, CC_CODE, LINE_CODE, EQUIP_SHORT_NAME, EQUIP_INSTALL_DATE, EQUIP_PROCESS_NUMBER, DEPT_CODE_OP, DEPT_CODE_USE, COMP_CODE_VENDER, COMP_CODE_AGENT, LAST_DTTM, INPUT_DIV) 
--		SELECT B.AREA_CODE, B.FACTORY_CODE, B.EQUIP_CODE, B.EQUIP_NAME, B.ASSET_CODE, B.EQUIP_DIV_CODE, B.EQUIP_SPEC, B.EQUIP_USE, B.CC_CODE, B.LINE_CODE, B.EQUIP_SHORT_NAME, CONVERT(VARCHAR(8),B.EQUIP_INSTALL_DATE,2), B.EQUIP_PROCESS_NUMBER, B.DEPT_CODE_OP, B.DEPT_CODE_USE, B.COMP_CODE_VENDER, B.COMP_CODE_AGENT, @AAA, 'A'
--		FROM EQUIP_MASTER_UPLOAD A, INSERTED B
--		WHERE (A.AREA_CODE = B.AREA_CODE) AND A.FACTORY_CODE=B.FACTORY_CODE AND  A.EQUIP_CODE=B.EQUIP_CODE AND A.UP_DIV='Y'
--	END
--else
	BEGIN
		INSERT INTO EQUIP_MASTER_UPLOAD(AREA_CODE, FACTORY_CODE, EQUIP_CODE, EQUIP_NAME, ASSET_CODE, EQUIP_DIV_CODE, EQUIP_SPEC, EQUIP_USE, CC_CODE, LINE_CODE, EQUIP_SHORT_NAME, EQUIP_INSTALL_DATE, EQUIP_PROCESS_NUMBER, DEPT_CODE_OP, DEPT_CODE_USE, COMP_CODE_VENDER, COMP_CODE_AGENT, UP_DIV,LAST_DTTM, INPUT_DIV) 
		SELECT AREA_CODE, FACTORY_CODE, EQUIP_CODE, EQUIP_NAME, ASSET_CODE, EQUIP_DIV_CODE, EQUIP_SPEC, EQUIP_USE, CC_CODE, LINE_CODE, EQUIP_SHORT_NAME, CONVERT(VARCHAR(8),EQUIP_INSTALL_DATE,2), EQUIP_PROCESS_NUMBER, DEPT_CODE_OP, DEPT_CODE_USE, COMP_CODE_VENDER, COMP_CODE_AGENT,'N', @AAA,'A'
		FROM INSERTED
		WHERE FACTORY_CODE <> 'R'
	END
--UPDATE EQUIP_MASTER_UPLOAD 
--SET INPUT_DIV = 'A'
--FROM EQUIP_MASTER_UPLOAD A, INSERTED B
--WHERE (A.AREA_CODE = B.AREA_CODE) AND A.FACTORY_CODE=B.FACTORY_CODE AND  A.EQUIP_CODE=B.EQUIP_CODE  AND A.LAST_DTTM= @AAA







GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

