USE [cmms]
GO
/****** Object:  Trigger [dbo].[TRIGGER_UPLOAD2]    Script Date: 03/28/2012 15:03:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER  TRIGGER [dbo].[TRIGGER_UPLOAD2] ON [dbo].[equip_master] 
FOR UPDATE
AS
DECLARE @AAA DATETIME
SELECT @AAA = GETDATE()
IF EXISTS(
	SELECT TOP 1 A.EQUIP_CODE
	FROM EQUIP_MASTER_UPLOAD A, INSERTED B
	WHERE A.AREA_CODE = B.AREA_CODE AND A.FACTORY_CODE=B.FACTORY_CODE AND  A.EQUIP_CODE=B.EQUIP_CODE AND 
		A.UP_DIV='N' AND A.INPUT_DIV='R')
	BEGIN
		UPDATE EQUIP_MASTER_UPLOAD 
		SET EQUIP_NAME=B.EQUIP_NAME, ASSET_CODE=B.ASSET_CODE, EQUIP_DIV_CODE=B.EQUIP_DIV_CODE, EQUIP_SPEC=B.EQUIP_SPEC, EQUIP_USE=B.EQUIP_USE, 
		       CC_CODE=B.CC_CODE, LINE_CODE=B.LINE_CODE, EQUIP_SHORT_NAME=B.EQUIP_SHORT_NAME, EQUIP_INSTALL_DATE=CONVERT(VARCHAR(8),B.EQUIP_INSTALL_DATE,2), 
		       EQUIP_PROCESS_NUMBER=B.EQUIP_PROCESS_NUMBER, DEPT_CODE_OP=B.DEPT_CODE_OP, DEPT_CODE_USE=B.DEPT_CODE_USE, 
		       COMP_CODE_VENDER=B.COMP_CODE_VENDER, COMP_CODE_AGENT=B.COMP_CODE_AGENT, INPUT_DIV='R'
		FROM EQUIP_MASTER_UPLOAD A, INSERTED B
		WHERE (A.AREA_CODE = B.AREA_CODE) AND A.FACTORY_CODE=B.FACTORY_CODE AND  A.EQUIP_CODE=B.EQUIP_CODE AND A.UP_DIV='N' AND A.INPUT_DIV='R'  --AND A.LAST_DTTM=GETDATE()
	END
ELSE
-- 장비번호 같고 'Y'인경우: 새로넣어준다
	BEGIN
		INSERT INTO EQUIP_MASTER_UPLOAD(AREA_CODE, FACTORY_CODE, EQUIP_CODE, EQUIP_NAME, ASSET_CODE, EQUIP_DIV_CODE, EQUIP_SPEC, EQUIP_USE, CC_CODE, LINE_CODE, EQUIP_SHORT_NAME, EQUIP_INSTALL_DATE, EQUIP_PROCESS_NUMBER, DEPT_CODE_OP, DEPT_CODE_USE, COMP_CODE_VENDER, COMP_CODE_AGENT, UP_DIV, LAST_DTTM, INPUT_DIV) 
		SELECT AREA_CODE, FACTORY_CODE, EQUIP_CODE, EQUIP_NAME, ASSET_CODE, EQUIP_DIV_CODE, EQUIP_SPEC, EQUIP_USE, CC_CODE, LINE_CODE, EQUIP_SHORT_NAME, CONVERT(VARCHAR(8),EQUIP_INSTALL_DATE,2), EQUIP_PROCESS_NUMBER, DEPT_CODE_OP, DEPT_CODE_USE, COMP_CODE_VENDER, COMP_CODE_AGENT, 'N',@AAA,'R'
		FROM INSERTED
	END