/*
  file name : sp_use_master_insert.sql
  system    : cmms system
  procedure name  : sp_use_master_insert
  description :
  use database  : cmms
  use program :
  parameter :
  use table :
  initial   : 2002.12
  author    :
*/

if exists (select * from sysobjects
      where id = object_id(N'[dbo].[sp_use_master_insert]')
        and objectproperty(id, N'isprocedure') = 1)
  drop procedure [dbo].[sp_use_master_insert]
go

/*
execute sp_use_master_insert
*/

create PROCEDURE [dbo].[sp_use_master_insert]
AS
BEGIN -- BEGIN PROCEDURE

  TRUNCATE TABLE USED_MASTER

  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','A',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','R',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','F',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','M',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','S',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','H',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'D','V',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'J','M',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'J','S',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'J','H',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
  INSERT INTO USED_MASTER(AREA_CODE, FACTORY_CODE, USED_CODE, USED_NAME)
  SELECT 'Y','Y',CODEID, CODENAME
  FROM IPIS.DBO.TMSTCODE
  WHERE CODEGROUP='DAC092'
  
END -- END PROCEDURE
