CREATE TABLE "WIP010" ("WHYEAR" CHAR(4) NOT NULL, "WHMONTH" CHAR(2) NOT NULL, "WHCMCD" CHAR(2) NOT NULL, "WHPLANT" CHAR(1) NOT NULL, 
"WHDVSN" CHAR(1) NOT NULL, "WHORCT" CHAR(4) NOT NULL, "WHCHARGE" CHAR(30) NOT NULL, "WHDEPT" CHAR(30) NOT NULL, "WHBRANCH" CHAR(30) NOT NULL,
"WHEMPT" CHAR(6) NOT NULL, "WHEMPTNM" CHAR(10) NOT NULL, "WHEMPM" CHAR(6) NOT NULL, 
"WHEMPMNM" CHAR(10) NOT NULL, "WHEMPB" CHAR(6) NOT NULL, "WHEMPBNM" CHAR(10) NOT NULL, "WHIPADDR" CHAR(30) NOT NULL, 
"WHMACADDR" CHAR(30) NOT NULL, "WHINPTDT" CHAR(8) NOT NULL, "WHUPDTID" CHAR(6) NOT NULL, "WHUPDTDT" CHAR(8) NOT NULL , 
PRIMARY KEY ("WHYEAR", "WHMONTH", "WHCMCD", "WHPLANT", "WHDVSN", "WHORCT")) ;
CREATE UNIQUE INDEX "WIP010" ON "WIP010" ("WHYEAR", "WHMONTH", "WHCMCD", "WHPLANT", "WHDVSN", "WHORCT") ;
DELETE FROM "PBCOMMON".pbcattbl WHERE PBT_TNAM = 'WIP010';
DELETE FROM "PBCOMMON".pbcatCOL WHERE PBC_TNAM = 'WIP010';
insert into "PBCOMMON".pbcattbl (pbt_tnam, pbt_ownr, pbd_fhgt, pbd_fwgt, pbd_fitl, pbd_funl, pbd_fchr, pbd_fptc, pbd_ffce, pbh_fhgt, pbh_fwgt, pbh_fitl, pbh_funl, pbh_fchr, pbh_fptc, pbh_ffce, pbl_fhgt, pbl_fwgt, pbl_fitl, pbl_funl, pbl_fchr, pbl_fptc, pbl_ffce, pbt_cmnt) values ('WIP010', 'PBWIP', -10, 400, 'N', 'N', 0, 34, '굴림체          ', -10, 400, 'N', 'N', 0, 34, '굴림체          ', -10, 400 , 'N', 'N', 0, 34, '굴림체          ', '재공실사 계수자 DB') ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHYEAR', '실사년도', 23 , '실사년도', 25, 25 , 0 , 0 , 0 , 'N', '실사년도' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHMONTH', '실사월', 23 , '실사월', 25, 25 , 0 , 0 , 0 , 'N', '실사월' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHCMCD', '회사', 23 , '회사', 25, 25 , 0 , 0 , 0 , 'N', '회사' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHPLANT', '지역', 23 , '지역', 25, 25 , 0 , 0 , 0 , 'N', '지역' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHDVSN', '공장', 23 , '공장', 25, 25 , 0 , 0 , 0 , 'N', '공장' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHORCT', '조코드', 23 , '조코드', 25, 25 , 0 , 0 , 0 , 'N', '조코드' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHCHARGE', '담당', 23 , '담당', 25, 25 , 0 , 0 , 0 , 'N', '담당' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHDEPT', '부', 23 , '부', 25, 25 , 0 , 0 , 0 , 'N', '부' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHBRANCH', '과', 23 , '과', 25, 25 , 0 , 0 , 0 , 'N', '과' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPT', '계수팀장', 23 , '계수팀장', 25, 25 , 0 , 0 , 0 , 'N', '계수팀장' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPTNM', '계수팀장명', 23 , '계수팀장명', 25, 25 , 0 , 0 , 0 , 'N', '계수팀장명' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPM', '계수반장', 23 , '계수반장', 25, 25 , 0 , 0 , 0 , 'N', '계수반장' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPMNM', '계수반장명', 23 , '계수반장명', 25, 25 , 0 , 0 , 0 , 'N', '계수반장명' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPB', '계수자', 23 , '계수자', 25, 25 , 0 , 0 , 0 , 'N', '계수자' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHEMPBNM', '계수자명', 23 , '계수자명', 25, 25 , 0 , 0 , 0 , 'N', '계수자명' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHIPADDR', 'IP ADDRESS', 23 , 'IP ADDRESS', 25, 25 , 0 , 0 , 0 , 'N', 'IPADDRESS' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHMACADDR', '장비번호', 23 , '장비번호', 25, 25 , 0 , 0 , 0 , 'N', '장비번호' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHINPTDT', '입력일', 23 , '입력일', 25, 25 , 0 , 0 , 0 , 'N', '입력일' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHUPDTID', '수정자', 23 , '수정자', 25, 25 , 0 , 0 , 0 , 'N', '수정자' ) ;
insert into "PBCOMMON".pbcatcol (pbc_tnam, pbc_ownr, pbc_cnam, pbc_labl, pbc_lpos, pbc_hdr, pbc_hpos, pbc_jtfy, pbc_case, pbc_hght, pbc_wdth, pbc_bmap, pbc_cmnt ) values ('WIP010', 'PBWIP', 'WHUPDTDT', '수정일', 23 , '수정일', 25, 25 , 0 , 0 , 0 , 'N', '수정일' ) ;
