CREATE TABLE "WIP012" ("WFYEAR" CHAR(4) NOT NULL, "WFMONTH" CHAR(2) NOT NULL, "WFCMCD" CHAR(2) NOT NULL, "WFPLANT" CHAR(1) NOT NULL,
"WFDVSN" CHAR(1) NOT NULL, "WFPITNO" CHAR(15) NOT NULL, "WFPCLS" CHAR(2) NOT NULL, "WFPSRC" CHAR(2) NOT NULL, "WFCITNO" CHAR(15) NOT NULL,
"WFCCLS" CHAR(2) NOT NULL, "WFCSRC" CHAR(2) NOT NULL,
"WFCONVQTY" DECIMAL(13,4) NOT NULL, "WFQTY1" DECIMAL(8,3) NOT NULL, "WFPQTY" DECIMAL(15,4) NOT NULL, "WFCQTY" DECIMAL(15,4) NOT NULL,
"CHGDATE" CHAR(30) NOT NULL,
PRIMARY KEY ("WFYEAR", "WFMONTH", "WFCMCD", "WFPLANT", "WFDVSN", "WFPITNO", "WFCITNO","CHGDATE")) ;
CREATE UNIQUE INDEX "WIP012" ON "WIP012" ("WFYEAR", "WFMONTH", "WFCMCD", "WFPLANT", "WFDVSN", "WFPITNO", "WFCITNO","CHGDATE") ;
