SELECT CC.PDCD, AA.WBITNO, DD.ITNM, DD.SPEC, CC.XUNIT, CC.CLS, CC.SRCE,
  BB.WBAVRG1 AS AVRG,
	DECIMAL(AA.WBINQT  / CC.CONVQTY,15,4) AS ADJINQT,
	DECIMAL(AA.WBINQT * BB.WBAVRG1,15,0) AS ADJINAT,
  DECIMAL(AA.WBUSQT1 / CC.CONVQTY,15,4) AS ADJUSQT1,
  DECIMAL(AA.WBUSQT1 * BB.WBAVRG1,15,0) AS ADJUSAT1,
  DECIMAL(AA.WBUSQT2 / CC.CONVQTY,15,4) AS ADJUSQT2,
  DECIMAL(AA.WBUSQT2 * BB.WBAVRG1,15,0) AS ADJUSAT2,
  DECIMAL(( AA.WBUSQT3 + AA.WBUSQT4 + AA.WBUSQT5 + AA.WBUSQT6 + AA.WBUSQT7 + AA.WBUSQT8 ) / CC.CONVQTY,15,4) AS ADJUSQT3,
  DECIMAL(( AA.WBUSQT3 + AA.WBUSQT4 + AA.WBUSQT5 + AA.WBUSQT6 + AA.WBUSQT7 + AA.WBUSQT8 ) * BB.WBAVRG1,15,0) AS ADJUSAT3,
	DECIMAL(AA.WBOHQT / CC.CONVQTY,15,4) AS ADJOHQT,
	DECIMAL(AA.WBOHQT * BB.WBAVRG1,15,0) AS ADJOHAT
FROM PBWIP.WIP013 AA INNER JOIN PBWIP.WIP002 BB
	ON AA.WBCMCD = BB.WBCMCD AND AA.WBPLANT = BB.WBPLANT AND
		AA.WBDVSN = BB.WBDVSN AND AA.WBITNO = BB.WBITNO AND
		AA.WBYEAR = BB.WBYEAR AND AA.WBMONTH = BB.WBMONTH AND
		AA.WBORCT = BB.WBORCT
	INNER JOIN PBINV.INV101 CC
	ON AA.WBCMCD = CC.COMLTD AND AA.WBPLANT = CC.XPLANT AND
		AA.WBDVSN = CC.DIV AND AA.WBITNO = CC.ITNO
	INNER JOIN PBINV.INV002 DD
	ON AA.WBCMCD = DD.COMLTD AND AA.WBITNO = DD.ITNO
WHERE AA.WBYEAR = '2007' AND AA.WBMONTH = '12' AND 
		AA.WBPLANT = 'D' AND AA.WBDVSN = 'A';
