select SUBSTR(TDTE4,1,4)||'.'||SUBSTR(TDTE4,5,2)||'.'||'01',bb.XPLANT,
	BB.DIV,' ',BB.ITNO,BB.DEPT, 
	CASE LENGTH(BB.SLNO)
		WHEN 10 THEN SUBSTR(BB.SLNO,3,1)
		ELSE SUBSTR(BB.SLNO,2,1)
	END
	,' ',0,0,
		SUM(CASE BB.SLIPTYPE
			WHEN 'SA' THEN TQTY4
			WHEN 'SR' THEN (-1) * TQTY4
			ELSE 0
			END ),'000030'
from PBINV.INV401 BB
where BB.COMLTD = '01' AND BB.SLIPTYPE IN ('SA','SR') AND
		BB.TDTE4 >= '20020101' AND BB.TDTE4 <= '20020131'
group by SUBSTR(TDTE4,1,4)||'.'||SUBSTR(TDTE4,5,2)||'.'||'01',bb.xplant,bb.div,bb.itno,
         BB.DEPT,CASE LENGTH(BB.SLNO)
							WHEN 10 THEN SUBSTR(BB.SLNO,3,1)
							ELSE SUBSTR(BB.SLNO,2,1)
							END;


