SELECT WDPRSRTY, WDPRSRNO, WDPRSRNO1, WDPRSRNO2, WDPRNO, WDDATE, WDPRQT, COUNT(WDITNO), SUM(WDCHQT), SUM(WDCHQT) / WDPRQT
FROM PBWIP.WIP004
WHERE WDPLANT = 'D' AND WDDVSN = 'A' AND WDDATE >= '20030201' AND WDDATE <= '20030227'
GROUP BY WDPRSRTY, WDPRSRNO, WDPRSRNO1, WDPRSRNO2, WDPRNO, WDDATE, WDPRQT
ORDER BY WDPRNO, WDDATE;
