  SELECT AAA."WBCMCD",   
         AAA."WBPLANT",   
         AAA."WBDVSN",   
         AAA."WBORCT",   
         AAA."WBITNO",
			CCC."WASCRP",
			CCC."WARETN",
			BBB."WBBGQT" BGQT,
			BBB."WBINQT" + AAA."WBINQT" + CCC."WAINQT" INQT,
			BBB."WBUSQT2" + AAA."WBUSQT2" + CCC."WAUSQT2" USQT2,
			BBB."WBUSQT7" + AAA."WBUSQT7" + CCC."WAUSQT7" USQT7,
			CCC."WAOHQT" OHQT
    FROM "PBWIP"."WIP002" AAA, "PBWIP"."WIP002" BBB, "PBWIP"."WIP001" CCC
	WHERE AAA."WBCMCD" = BBB."WBCMCD" AND
			AAA."WBPLANT" = BBB."WBPLANT" AND
			AAA."WBDVSN" = BBB."WBDVSN" AND
			AAA."WBORCT" = BBB."WBORCT" AND
			AAA."WBITNO" = BBB."WBITNO" AND
			AAA."WBIOCD" = BBB."WBIOCD" AND
			BBB."WBCMCD" = CCC."WACMCD" AND
			BBB."WBPLANT" = CCC."WAPLANT" AND
			BBB."WBDVSN" = CCC."WADVSN" AND
			BBB."WBORCT" = CCC."WAORCT" AND
			BBB."WBITNO" = CCC."WAITNO" AND
			BBB."WBIOCD" = CCC."WAIOCD" AND
			AAA."WBIOCD" = '2' AND
			AAA."WBCMCD" = :a_cmcd AND
			AAA."WBYEAR"||AAA."WBMONTH" = :a_date2 AND
			BBB."WBYEAR"||BBB."WBMONTH" = :a_date1 AND
			NOT ( BBB."WBBGQT" = 0 AND BBB."WBINQT" = 0 AND AAA."WBINQT" = 0 AND CCC."WAINQT" = 0 AND
					BBB."WBUSQT2" = 0 AND  AAA."WBUSQT2" = 0 AND  CCC."WAUSQT2" = 0 AND
					BBB."WBUSQT7" = 0 AND  AAA."WBUSQT7" = 0 AND  CCC."WAUSQT7" = 0 )
UNION ALL
	SELECT AAA."WBCMCD",   
         AAA."WBPLANT",   
         AAA."WBDVSN",   
         AAA."WBORCT",   
         AAA."WBITNO",
			CCC."WASCRP",
			CCC."WARETN",
			AAA."WBBGQT" BGQT,
			AAA."WBINQT" + CCC."WAINQT" INQT,
			AAA."WBUSQT2" + CCC."WAUSQT2" USQT2,
			AAA."WBUSQT7" + CCC."WAUSQT7" USQT7,
			CCC."WAOHQT" OHQT
    FROM "PBWIP"."WIP002" AAA, "PBWIP"."WIP001" CCC
	WHERE AAA."WBCMCD" = CCC."WACMCD" AND
			AAA."WBPLANT" = CCC."WAPLANT" AND
			AAA."WBDVSN" = CCC."WADVSN" AND
			AAA."WBORCT" = CCC."WAORCT" AND
			AAA."WBITNO" = CCC."WAITNO" AND
			AAA."WBIOCD" = CCC."WAIOCD" AND
			AAA."WBCMCD" = :a_cmcd AND
			AAA."WBYEAR"||AAA."WBMONTH" = :a_date2 AND
			AAA."WBIOCD" = '2' AND
			(NOT EXISTS ( SELECT  *
								FROM "PBWIP"."WIP002" BBB
								WHERE AAA."WBCMCD" = BBB."WBCMCD" AND
										AAA."WBPLANT" = BBB."WBPLANT" AND
										AAA."WBDVSN" = BBB."WBDVSN" AND
										AAA."WBORCT" = BBB."WBORCT" AND
										AAA."WBITNO" = BBB."WBITNO" AND
										AAA."WBIOCD" = BBB."WBIOCD" AND
										BBB."WBCMCD" = :a_cmcd AND
										BBB."WBYEAR"||BBB."WBMONTH" = :a_date1 AND
										BBB."WBIOCD" = '2' )) AND
			(NOT AAA."WBBGQT" = 0 AND AAA."WBINQT" = 0 AND CCC."WAINQT" = 0 AND 
				  AAA."WBUSQT2" = 0 AND CCC."WAUSQT2" = 0 AND AAA."WBUSQT7" = 0 AND CCC."WAUSQT7" = 0 )
UNION ALL
	SELECT CCC."WACMCD",   
         CCC."WAPLANT",   
         CCC."WADVSN",   
         CCC."WAORCT",   
         CCC."WAITNO",
			CCC."WASCRP",
			CCC."WARETN",
			CCC."WABGQT" BGQT,
			CCC."WAINQT" INQT,
			CCC."WAUSQT2" USQT2,
			CCC."WAUSQT7" USQT7,
			CCC."WAOHQT" OHQT 
    FROM "PBWIP"."WIP001" CCC
	WHERE CCC."WACMCD" = :a_cmcd AND
			CCC."WAIOCD" = '2' AND
			(NOT EXISTS ( SELECT  *
								FROM "PBWIP"."WIP002" BBB
								WHERE CCC."WACMCD" = BBB."WBCMCD" AND
										CCC."WAPLANT" = BBB."WBPLANT" AND
										CCC."WADVSN" = BBB."WBDVSN" AND
										CCC."WAORCT" = BBB."WBORCT" AND
										CCC."WAITNO" = BBB."WBITNO" AND
										BBB."WBCMCD" = :a_cmcd AND
										BBB."WBYEAR"||BBB."WBMONTH" = :a_date1 AND
										BBB."WBIOCD" = '2' )) AND
			(NOT CCC."WABGQT" = 0 AND CCC."WAINQT" = 0 AND CCC."WAUSQT2" = 0 AND CCC."WAUSQT7" = 0)