SELECT WCPLANT,WCDVSN,SUM(WCBGAT1 + WCINAT1 - ( WCUSAT1 + WCUSAT2 + WCUSAT3 +
WCUSAT4 + WCUSAT5 + WCUSAT6 + WCUSAT7 + WCUSAT8 + WCUSAT9))
FROM PBWIP.WIP003
WHERE WCCMCD = '01' AND WCYEAR = '2004' AND WCMONTH = '11' 
GROUP BY WCPLANT,WCDVSN
ORDER BY WCPLANT,WCDVSN;
//SELECT WCPLANT,WCDVSN,SUM(WCBGAT1)
//FROM PBWIP.WIP003
//WHERE WCCMCD = '01' AND WCYEAR = '2004' AND WCMONTH = '12' 
//GROUP BY WCPLANT,WCDVSN
//ORDER BY WCPLANT,WCDVSN;

// BOM 레벨 체크
//SELECT DISTINCT A.WDITNO, B.LOLEVEL
//FROM PBWIP.WIP004 A INNER JOIN PBINV.INV002 B
//	ON A.WDCMCD = B.COMLTD AND A.WDITNO = B.ITNO
//WHERE A.WDCMCD = '01' AND A.WDPLANT = 'D' AND A.WDDVSN = 'M' AND
//	A.WDPRNO = '96472324-1' AND WDDATE >= '20120801';

//SELECT A.PPITN, B.LOLEVEL
//FROM PBPDM.BOM001 A INNER JOIN PBINV.INV002 B
//	ON A.PCMCD = B.COMLTD AND A.PPITN = B.ITNO
//WHERE A.PCMCD = '01' AND A.PCITN = '96574700P';

//SELECT * FROM PBINV.INV002
//WHERE COMLTD = '01' AND ITNO = '96574700P';