SELECT WCPLANT,WCDVSN,SUM(WCBGAT1 + WCINAT1 - ( WCUSAT1 + WCUSAT2 + WCUSAT3 +
WCUSAT4 + WCUSAT5 + WCUSAT6 + WCUSAT7 + WCUSAT8 + WCUSAT9))
FROM PBWIP.WIP003
WHERE WCCMCD = '01' AND WCYEAR = '2004' AND WCMONTH = '11' 
GROUP BY WCPLANT,WCDVSN
ORDER BY WCPLANT,WCDVSN;
//SELECT WCPLANT,WCDVSN,SUM(WCBGAT1)
//FROM PBWIP.WIP003
//WHERE WCCMCD = '01' AND WCYEAR = '2004' AND WCMONTH = '12' 
//GROUP BY WCPLANT,WCDVSN
//ORDER BY WCPLANT,WCDVSN;