SELECT  CARITEM,ACCOUNTDATE,REASONITEMCODE,PRODUCTGROUP,NATIONCODE,CARCODE,CARDISTANCE,
	SUM(PAYQTY),SUM(PAYAMOUNT),SUM(CONFIRMQTY),SUM(CONFIRMAMOUNT)
FROM TQMANAGEMASTER
WHERE EXPORTGUBUN = 'E' AND OAGUBUN = 'O' AND KDACCUSTOMER = 'L10500' 
AND ACCOUNTDATE >= '2006.01' AND ACCOUNTDATE <= '2006.12'
GROUP BY CARITEM,ACCOUNTDATE,REASONITEMCODE,PRODUCTGROUP,NATIONCODE,CARCODE,CARDISTANCE

