--공제전
SELECT BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZLEVEL,AA.ZITNO,AA.ZDESC,
AA.ZSPEC,AA.ZSRCE,AA.ZMOVCOST,AA.ZUNITQTY,AA.ZWKCT,
DECIMAL(truncate( CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce <> '01' THEN
	DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3)
ELSE 0 END,3),15,3) AS DOMCST,
DECIMAL(truncate(CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce = '01' THEN
	DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3)
ELSE 0 END,3),15,3) AS EXPCST,
AA.ZCALC,AA.ZEXPLANT,AA.ZEXDIV
FROM PBPDM.BOM015 AA RIGHT OUTER JOIN
	(SELECT COMLTD,CUSTCD,CITNO,CITNM,XPLANT,DIV,ITNO FROM PBSLE.SLE101
	WHERE COMLTD = '01' AND CUSTCD IN ('L10500','L10502','L11100') AND COSTDIV IN ('H','B','K','O','T')) BB
ON AA.ZCMCD = BB.COMLTD AND AA.ZPLANT = BB.XPLANT AND 
		AA.ZDIV = BB.DIV AND AA.ZMDNO = BB.ITNO AND AA.ZDATE = '200912'
ORDER BY BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZSERIAL;

-- 공제후
SELECT BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZLEVEL,AA.ZITNO,AA.ZDESC,
AA.ZSPEC,AA.ZSRCE,AA.ZMOVCOST,AA.ZUNITQTY,AA.ZWKCT,
DECIMAL(truncate( CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce <> '01' THEN
	CASE AA.ZCOMCD = 'Y' THEN 0 ELSE DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3) END
ELSE 
  CASE WHEN AA.ZCALC = 'N' AND AA.ZSRCE <> '01' THEN
    CASE AA.ZCOMCD = 'Y' THEN (-1) * DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3) ELSE 0 END
  ELSE 0 END
END,3),15,3) AS DOMCST,
DECIMAL(truncate(CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce = '01' THEN
	CASE AA.ZCOMCD = 'Y' THEN 0 ELSE DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3) END
ELSE 
  CASE WHEN AA.ZCALC = 'N' AND AA.ZSRCE = '01' THEN 
    CASE AA.ZCOMCD = 'Y' THEN (-1) * DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3) ELSE 0 END
  ELSE 0 END
END,3),15,3) AS EXPCST,
AA.ZCALC
FROM PBPDM.BOM015 AA RIGHT OUTER JOIN
	(SELECT COMLTD,CUSTCD,CITNO,CITNM,XPLANT,DIV,ITNO FROM PBSLE.SLE101
	WHERE COMLTD = '01' AND CUSTCD IN ('L10500','L10502','L11100') AND COSTDIV IN ('H','B','K','O','T')) BB
ON AA.ZCMCD = BB.COMLTD AND AA.ZPLANT = BB.XPLANT AND 
		AA.ZDIV = BB.DIV AND AA.ZMDNO = BB.ITNO AND AA.ZDATE = '200912'
ORDER BY BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZSERIAL;

-- 전사기준 영업팀 제공거래처품번
SELECT BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZLEVEL,AA.ZITNO,AA.ZDESC,
AA.ZSPEC,AA.ZSRCE,AA.ZMOVCOST,AA.ZUNITQTY,AA.ZWKCT,
DECIMAL(truncate( CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce <> '01' THEN
	DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3)
ELSE 0 END,3),15,3) AS DOMCST,
DECIMAL(truncate(CASE WHEN AA.zcalc = 'Y' and  AA.Zsrce = '01' THEN
	DECIMAL(REPLACE(AA.zmovcost,',',''),15,6) * DECIMAL(REPLACE(AA.zunitqty,',',''),15,3)
ELSE 0 END,3),15,3) AS EXPCST,
AA.ZCALC,AA.ZEXPLANT,AA.ZEXDIV,CC.ZPVEND
FROM PBPDM.BOM015 AA RIGHT OUTER JOIN
	(SELECT COMLTD,F1 AS CUSTCD,CAST(F2 AS VARCHAR(12)) AS CITNO,CITNM,XPLANT,DIV,ITNO 
FROM PBSLE.SLE101 RIGHT OUTER JOIN PBTEST.TEST01
	ON CUSTCD = F1 AND CITNO = CAST(F2 AS VARCHAR(12))) BB
ON AA.ZCMCD = BB.COMLTD AND AA.ZPLANT = BB.XPLANT AND 
		AA.ZDIV = BB.DIV AND AA.ZMDNO = BB.ITNO AND AA.ZDATE = '200912'
LEFT OUTER JOIN ( SELECT DISTINCT ZCMCD, ZPLANT, ZDIV, ZITNO, ZPVEND FROM PBPDM.BOMT13
		WHERE ZCMCD = '01' AND ZDATE = '200912' AND ZPVEND <> '') CC
	ON AA.ZCMCD = CC.ZCMCD AND AA.ZEXPLANT = CC.ZPLANT AND 
		AA.ZEXDIV = CC.ZDIV AND AA.ZITNO = CC.ZITNO
ORDER BY BB.CUSTCD,BB.CITNO,BB.CITNM,BB.XPLANT,BB.DIV,BB.ITNO,AA.ZSERIAL;