SELECT AA.WBPLANT, AA.WBDVSN, AA.WBITNO, CC.PDCD, EE.PRNAME, DD.ITNM, DD.SPEC, CC.CLS, CC.SRCE,
DECIMAL(BB.WBAVRG1 * CC.CONVQTY,15,2) AS AVRG, 
DECIMAL(AA.WBBGQT / CC.CONVQTY,15,4) AS BGQT, 
DECIMAL(AA.WBINQT / CC.CONVQTY,15,4) AS INQT, 
DECIMAL(AA.WBUSQT1 / CC.CONVQTY,15,4) AS USQT1, 
DECIMAL(AA.WBUSQT2 / CC.CONVQTY,15,4) AS USQT2,
DECIMAL(	( AA.WBUSQT3 + AA.WBUSQT4 + AA.WBUSQT5 + AA.WBUSQT6 + AA.WBUSQT7 + AA.WBUSQT8) / CC.CONVQTY,15,4) AS USQT3,
DECIMAL(AA.WBOHQT / CC.CONVQTY,15,4) AS  OHQT
FROM PBWIP.WIP013 AA LEFT OUTER JOIN PBWIP.WIP002 BB
	ON AA.WBYEAR = BB.WBYEAR AND AA.WBMONTH = BB.WBMONTH AND AA.WBCMCD = BB.WBCMCD AND
	AA.WBPLANT = BB.WBPLANT AND AA.WBDVSN = BB.WBDVSN AND AA.WBORCT = BB.WBORCT AND
	AA.WBITNO = BB.WBITNO
	INNER JOIN PBINV.INV101 CC
	ON AA.WBCMCD = CC.COMLTD AND AA.WBPLANT = CC.XPLANT AND AA.WBDVSN = CC.DIV AND
		AA.WBITNO = CC.ITNO
	INNER JOIN PBINV.INV002 DD
	ON AA.WBCMCD = DD.COMLTD AND AA.WBITNO = DD.ITNO
	INNER JOIN PBCOMMON.DAC007 EE
	ON CC.PDCD = EE.PRPRCD
	INNER JOIN ( SELECT DISTINCT TPLNT AS WBPLANT, TDVSN AS WBDVSN, TCITN AS WBITNO FROM PBWIP.WIP015 ) FF
	ON AA.WBPLANT = FF.WBPLANT AND AA.WBDVSN = FF.WBDVSN AND AA.WBITNO = FF.WBITNO
WHERE AA.WBYEAR = '2008' AND AA.WBMONTH = '08';


SELECT ZZ.ZPLANT, ZZ.ZDIV, ZZ.ZITNO
FROM PBPDM.BOM013 ZZ INNER JOIN 
( select  distinct zcmcd,zplant,zdiv,zmdno
from    pbpdm.bom013,pbinv.inv101 
where   zcmcd = '01' and zdate = '200807' and zplant||zdiv||zitno in 
(   SELECT  DISTINCT A.XPLANT||A.DIV||A.ITNO FROM PBINV.INV402 A,PBINV.INV401 B
    WHERE   A.COMLTD = B.COMLTD AND A.XPLANT = B.XPLANT AND A.DIV = B.DIV AND A.ITNO = B.ITNO AND
                A.COMLTD = '01' AND A.XYEAR = '200807' AND B.VSRNO =  'D2062'   AND B.SLIPTYPE='RP' AND B.CLS='10' AND B.SRCE IN ('02','04')
) and zcmcd = comltd and zplant = xplant and zdiv = div and zmdno = itno and cls = '30' ) XX
ON ZZ.ZCMCD = XX.ZCMCD AND ZZ.ZPLANT = XX.ZPLANT AND ZZ.ZDIV = XX.ZDIV AND
	ZZ.ZMDNO = XX.ZMDNO AND ZZ.ZDATE = '200807'
;


SELECT AA.WBPLANT, AA.WBDVSN, AA.WBITNO, CC.PDCD, EE.PRNAME, DD.ITNM, DD.SPEC, CC.CLS, CC.SRCE,
DECIMAL(BB.WBAVRG1 * CC.CONVQTY,15,2) AS AVRG, 
DECIMAL(AA.WBBGQT / CC.CONVQTY,15,4) AS BGQT, 
DECIMAL(AA.WBINQT / CC.CONVQTY,15,4) AS INQT, 
DECIMAL(AA.WBUSQT1 / CC.CONVQTY,15,4) AS USQT1, 
DECIMAL(AA.WBUSQT2 / CC.CONVQTY,15,4) AS USQT2,
DECIMAL(	( AA.WBUSQT3 + AA.WBUSQT4 + AA.WBUSQT5 + AA.WBUSQT6 + AA.WBUSQT7 + AA.WBUSQT8) / CC.CONVQTY,15,4) AS USQT3,
DECIMAL(AA.WBOHQT / CC.CONVQTY,15,4) AS  OHQT
FROM PBWIP.WIP013 AA LEFT OUTER JOIN PBWIP.WIP002 BB
	ON AA.WBYEAR = BB.WBYEAR AND AA.WBMONTH = BB.WBMONTH AND AA.WBCMCD = BB.WBCMCD AND
	AA.WBPLANT = BB.WBPLANT AND AA.WBDVSN = BB.WBDVSN AND AA.WBORCT = BB.WBORCT AND
	AA.WBITNO = BB.WBITNO
	INNER JOIN PBINV.INV101 CC
	ON AA.WBCMCD = CC.COMLTD AND AA.WBPLANT = CC.XPLANT AND AA.WBDVSN = CC.DIV AND
		AA.WBITNO = CC.ITNO
	INNER JOIN PBINV.INV002 DD
	ON AA.WBCMCD = DD.COMLTD AND AA.WBITNO = DD.ITNO
	INNER JOIN PBCOMMON.DAC007 EE
	ON CC.PDCD = EE.PRPRCD
	INNER JOIN ( SELECT DISTINCT ZZ.ZPLANT AS PLANT, ZZ.ZDIV AS DIV, ZZ.ZITNO AS ITNO
FROM PBPDM.BOM013 ZZ INNER JOIN 
( select  distinct zcmcd,zplant,zdiv,zmdno
from    pbpdm.bom013,pbinv.inv101 
where   zcmcd = '01' and zdate = '200807' and zplant||zdiv||zitno in 
(   SELECT  DISTINCT A.XPLANT||A.DIV||A.ITNO FROM PBINV.INV402 A,PBINV.INV401 B
    WHERE   A.COMLTD = B.COMLTD AND A.XPLANT = B.XPLANT AND A.DIV = B.DIV AND A.ITNO = B.ITNO AND
                A.COMLTD = '01' AND A.XYEAR = '200807' AND B.VSRNO =  'D2062'   AND B.SLIPTYPE='RP' AND B.CLS='10' AND B.SRCE IN ('02','04')
) and zcmcd = comltd and zplant = xplant and zdiv = div and zmdno = itno and cls = '30' ) XX
ON ZZ.ZCMCD = XX.ZCMCD AND ZZ.ZPLANT = XX.ZPLANT AND ZZ.ZDIV = XX.ZDIV AND
	ZZ.ZMDNO = XX.ZMDNO AND ZZ.ZDATE = '200807' ) FF
	ON AA.WBPLANT = FF.PLANT AND AA.WBDVSN = FF.DIV AND AA.WBITNO = FF.ITNO
WHERE AA.WBYEAR = '2008' AND AA.WBMONTH = '08';


SELECT DISTINCT WDPLANT,WDDVSN, WDPRNO, WDITNO, DECIMAL(WDCHQT/WDPRQT,15,3) AS PQTY FROM PBWIP.WIP004
WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN = 'A' AND
WDPRSRTY = 'RP' AND WDCHDPT = 'D2062' AND WDIOCD = '3' AND WDDATE >= '20080101' AND
WDDATE <= '20080731';

SELECT WDITNO, SUM(WDCHQT) FROM PBWIP.WIP004
WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN = 'M' AND WDDATE >= '20080801' AND
WDDATE <= '20080809' AND WDIOCD = '3' AND WDCHDPT = 'D2062'

SELECT 
( SELECT ITNO, SUM(CASE SLIPTYPE WHEN 'IS' THEN TQTY4 WHEN 'RS' THEN (-1) * TQTY4 ELSE 0 END) AS SUM_QTY
FROM PBINV.INV401
WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'M' AND VSRNO = 'D2062' AND
TDTE4 >= '20080801' AND TDTE4 <= '20080809' AND SLIPTYPE <> 'RP'
GROUP BY ITNO ) TMP_INV
;


select  zcmcd,zplant,zdiv,zmdno,zitno,zdate,zunitqty
from    pbpdm.bom013,pbinv.inv101 
where   zcmcd = '01' and zplant||zdiv||zitno in 
(   SELECT  DISTINCT A.XPLANT||A.DIV||A.ITNO FROM PBINV.INV402 A,PBINV.INV401 B
    WHERE   A.COMLTD = B.COMLTD AND A.XPLANT = B.XPLANT AND A.DIV = B.DIV AND A.ITNO = B.ITNO AND
                A.COMLTD = '01' AND A.XYEAR = '200807' AND B.VSRNO =  'D2062'   AND B.SLIPTYPE='RP' AND B.CLS='10' AND B.SRCE IN ('02','04')
) and zcmcd = comltd and zplant = xplant and zdiv = div and zmdno = itno and cls = '30' and zdate >= '200601'
order by zmdno, zitno


SELECT AA.WBITNO, AA.INQT + IFNULL(BB.SUM_QTY,0)
FROM
( SELECT WBITNO, SUM(WBINQT) AS INQT FROM PBWIP.WIP014
WHERE WBCMCD = '01' AND WBPLANT = 'D' AND WBDVSN = 'M' AND WBORCT = 'D2062' AND
WBYEAR = '2008' AND WBMONTH >= '01' AND WBMONTH <= '07'
GROUP BY WBITNO ) AA LEFT OUTER JOIN
( SELECT ITNO, SUM(CASE SLIPTYPE WHEN 'IS' THEN TQTY4 WHEN 'RS' THEN (-1) * TQTY4 ELSE 0 END) AS SUM_QTY
FROM PBINV.INV401
WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'M' AND VSRNO = 'D2062' AND
TDTE4 >= '20080801' AND TDTE4 <= '20080809' AND SLIPTYPE <> 'RP'
GROUP BY ITNO ) BB
ON AA.WBITNO = BB.ITNO;

SELECT AA.WBPLANT, AA.WBDVSN, AA.WBITNO, DD.PDCD, FF.PRNAME, EE.ITNM, EE.SPEC, DD.CLS, DD.SRCE,
AA.INQT + IFNULL(BB.SUM_QTY,0), IFNULL(CC.CHQT,0)
FROM
( SELECT WBPLANT,WBDVSN, WBITNO, SUM(WBINQT) AS INQT FROM PBWIP.WIP014
WHERE WBCMCD = '01' AND WBPLANT = 'D' AND WBDVSN = 'M' AND WBORCT = 'D2062' AND
WBYEAR = '2008' AND WBMONTH >= '01' AND WBMONTH <= '07'
GROUP BY WBPLANT,WBDVSN, WBITNO ) AA LEFT OUTER JOIN
( SELECT ITNO, SUM(CASE SLIPTYPE WHEN 'IS' THEN TQTY4 WHEN 'RS' THEN (-1) * TQTY4 ELSE 0 END) AS SUM_QTY
FROM PBINV.INV401
WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'M' AND VSRNO = 'D2062' AND
TDTE4 >= '20080801' AND TDTE4 <= '20080809' AND SLIPTYPE <> 'RP'
GROUP BY ITNO ) BB
ON AA.WBITNO = BB.ITNO
LEFT OUTER JOIN ( SELECT WDITNO, SUM(WDCHQT) AS CHQT FROM PBWIP.WIP004
WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN = 'M' AND WDDATE >= '20080801' AND
WDDATE <= '20080809' AND WDIOCD = '3' AND WDCHDPT = 'D2062'
GROUP BY WDITNO ) CC
ON  AA.WBITNO = CC.WDITNO
	INNER JOIN PBINV.INV101 DD
	ON AA.WBPLANT = DD.XPLANT AND AA.WBDVSN = DD.DIV AND
		AA.WBITNO = DD.ITNO
	INNER JOIN PBINV.INV002 EE
	ON AA.WBITNO = DD.ITNO
	INNER JOIN PBCOMMON.DAC007 FF
	ON DD.PDCD = FF.PRPRCD;


SELECT AA.WBPLANT, AA.WBDVSN, AA.WBITNO, DD.PDCD, FF.PRNAME, EE.ITNM, EE.SPEC, DD.CLS, DD.SRCE,
AA.AVRG, DECIMAL(AA.INQT / DD.CONVQTY,15,4) + IFNULL(BB.SUM_QTY,0), IFNULL(DECIMAL(CC.CHQT / DD.CONVQTY,15,4),0)
FROM
( SELECT WBPLANT,WBDVSN, WBITNO, SUM( CASE WBMONTH WHEN '07' THEN WBAVRG1 ELSE 0 END ) AS AVRG,
	SUM(WBINQT) AS INQT FROM PBWIP.WIP014
WHERE WBCMCD = '01' AND WBPLANT = 'D' AND WBDVSN = 'M' AND WBORCT = 'D2062' AND
WBYEAR = '2008' AND WBMONTH >= '01' AND WBMONTH <= '07'
GROUP BY WBPLANT,WBDVSN, WBITNO ) AA LEFT OUTER JOIN
( SELECT ITNO, SUM(CASE SLIPTYPE WHEN 'IS' THEN TQTY4 WHEN 'RS' THEN (-1) * TQTY4 ELSE 0 END) AS SUM_QTY
FROM PBINV.INV401
WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'M' AND VSRNO = 'D2062' AND
TDTE4 >= '20080801' AND TDTE4 <= '20080809' AND SLIPTYPE <> 'RP'
GROUP BY ITNO ) BB
ON AA.WBITNO = BB.ITNO
LEFT OUTER JOIN ( SELECT WDITNO, SUM(WDCHQT) AS CHQT FROM PBWIP.WIP004
WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN = 'M' AND WDDATE >= '20080801' AND
WDDATE <= '20080809' AND WDIOCD = '3' AND WDCHDPT = 'D2062'
GROUP BY WDITNO ) CC
ON  AA.WBITNO = CC.WDITNO
	INNER JOIN PBINV.INV101 DD
	ON AA.WBPLANT = DD.XPLANT AND AA.WBDVSN = DD.DIV AND
		AA.WBITNO = DD.ITNO
	INNER JOIN PBINV.INV002 EE
	ON AA.WBITNO = EE.ITNO
	INNER JOIN PBCOMMON.DAC007 FF
	ON DD.PDCD = FF.PRPRCD;

--2008.08.12

//SELECT DISTINCT WDPRSRTY,WDPRSRNO,WDPRSRNO1,WDPRSRNO2 FROM PBWIP.WIP004
//WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN = 'M' AND
//WDPRNO IN ('431954Y',
//'431955Y') AND WDDATE >= '20080801' AND WDDATE <= '20080809' AND
//WDITNO = '432559'
//ORDER BY WDPRSRTY,WDPRSRNO,WDPRSRNO1,WDPRSRNO2;

//SELECT * FROM PBPDM.BOM001
//WHERE PCITN = '432559';

SELECT SLIPTYPE,SRNO,SRNO1,SRNO2 FROM PBINV.INV401
WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'M' AND
ITNO IN ('431954Y',
'431955Y') AND SLIPTYPE = 'RP' AND TDTE4 >= '20080101' AND TDTE4 <= '20080809'
ORDER BY SLIPTYPE,SRNO,SRNO1,SRNO2;


SELECT WDPLANT,WDDVSN, WDITNO,
	SUM(CASE WHEN WDSLTY = 'WC' THEN WDCHQT ELSE 0 END) AS USQT,
	SUM(CASE WHEN WDSLTY = 'WR' THEN ( CASE WHEN WDINPTID = '' THEN WDCHQT ELSE 0 END ) ELSE 0 END) AS USQT_AUTO,
	SUM(CASE WHEN WDSLTY = 'WR' THEN ( CASE WHEN WDINPTID <> '' THEN WDCHQT ELSE 0 END ) ELSE 0 END) AS USQT_MAN
FROM PBWIP.WIP004
WHERE WDCMCD = '01' AND WDPLANT = 'D' AND WDDVSN IN ('A','M') AND
	WDDATE >= '20050101' AND WDDATE <= '20050131'
GROUP BY WDPLANT,WDDVSN, WDITNO;

SELECT SUBSTRING(AA.WDDATE,1,6), AA.WDPLANT, AA.WDDVSN, AA.WDITNO,
	DECIMAL(SUM(CASE WHEN AA.WDSLTY = 'WC' THEN AA.WDCHQT / BB.CONVQTY ELSE 0 END),15,2) AS USQT,
	DECIMAL((SUM(CASE WHEN AA.WDSLTY = 'WR' THEN 
	( CASE WHEN AA.WDINPTID = '' THEN AA.WDCHQT / BB.CONVQTY ELSE 0 END ) ELSE 0 END)),15,2) AS USQT_AUTO,
	DECIMAL(( SUM (CASE WHEN AA.WDSLTY = 'WR' THEN 
	( CASE WHEN AA.WDINPTID <> '' THEN AA.WDCHQT /BB.CONVQTY ELSE 0 END ) ELSE 0 END)),15,2) AS USQT_MAN
FROM PBWIP.WIP004 AA INNER JOIN PBINV.INV101 BB
	ON AA.WDCMCD = BB.COMLTD AND AA.WDPLANT = BB.XPLANT AND AA.WDDVSN = BB.DIV AND
	AA.WDITNO = BB.ITNO
WHERE AA.WDCMCD = '01' AND AA.WDPLANT = 'D' AND AA.WDDVSN IN ('A','M') AND AA.WDIOCD = '1' AND
	AA.WDDATE >= '20050101' AND AA.WDDATE <= '20051231' AND AA.WDITNO IN ( SELECT TCITN FROM PBWIP.WIP015 WHERE TLEVEL = 0 )
GROUP BY SUBSTRING(AA.WDDATE,1,6), AA.WDPLANT,AA.WDDVSN, AA.WDITNO;


SELECT SUBSTRING(AA.WDDATE,1,6), AA.WDPLANT, AA.WDDVSN, AA.WDITNO,
	DECIMAL(SUM(CASE WHEN AA.WDSLTY = 'WC' THEN AA.WDCHQT / BB.CONVQTY ELSE 0 END),15,2) AS USQT,
	DECIMAL((SUM(CASE WHEN AA.WDSLTY = 'WR' THEN 
	( CASE WHEN AA.WDINPTID = '' THEN AA.WDCHQT / BB.CONVQTY ELSE 0 END ) ELSE 0 END)),15,2) AS USQT_AUTO,
	DECIMAL(( SUM (CASE WHEN AA.WDSLTY = 'WR' THEN 
	( CASE WHEN AA.WDINPTID <> '' THEN AA.WDCHQT / BB.CONVQTY ELSE 0 END ) ELSE 0 END)),15,2) AS USQT_MAN
FROM PBWIP.WIP004 AA INNER JOIN PBINV.INV101 BB
	ON AA.WDCMCD = BB.COMLTD AND AA.WDPLANT = BB.XPLANT AND AA.WDDVSN = BB.DIV AND
	AA.WDITNO = BB.ITNO
	INNER JOIN PBWIP.WIP015 CC
	ON AA.WDCMCD = CC.TCMCD AND AA.WDPLANT = CC.TPLNT AND AA.WDDVSN = CC.TDVSN AND AA.WDITNO = CC.TCITN
		AND CC.TLEVEL = 0
WHERE AA.WDCMCD = '01' AND AA.WDPLANT = 'D' AND AA.WDDVSN IN ('A','M') AND AA.WDIOCD = '1' AND
	AA.WDDATE >= '20080101' AND AA.WDDATE <= '20080131'
GROUP BY SUBSTRING(AA.WDDATE,1,6), AA.WDPLANT,AA.WDDVSN, AA.WDITNO;

-- 2008.08.13

//SELECT TPLNT,TDVSN,TMODL,COUNT(*)
//FROM PBWIP.WIP015 INNER JOIN PBINV.INV101
//	ON TCMCD = COMLTD AND TPLNT = XPLANT AND TDVSN = DIV AND TCITN = ITNO AND CLS = '30'
//GROUP BY TPLNT,TDVSN,TMODL;

//SELECT TPLNT,TDVSN,TMODL,TCITN
//FROM PBWIP.WIP015 INNER JOIN PBINV.INV101
//	ON TCMCD = COMLTD AND TPLNT = XPLANT AND TDVSN = DIV AND TCITN = ITNO AND CLS = '30'
//WHERE TMODL = '18027382'
//ORDER BY TPLNT,TDVSN,TMODL,TCITN;

SELECT * FROM PBWIP.WIP015
WHERE TMODL = '18027382'
ORDER BY TSERL;

//SELECT * FROM PBPDM.BOM001
//WHERE PCITN = '18045875';

//SELECT * FROM PBINV.INV101
//WHERE COMLTD = '01' AND ITNO = '18045875';

--SELECT PBWIP.SF_WIP_REV('01','D','M','18027382','20080731','A') FROM PBCOMMON.COMM000
;
--SELECT * FROM PBWIP.WIP015 WHERE TMODL = '18027382' ORDER BY TSERL
;
--DELETE FROM PBWIP.WIP015
;
SELECT * FROM QTEMP.BOMTEMP01;

--SELECT TPLNT,TDVSN,TMODL,COUNT(*) FROM PBWIP.WIP015 INNER JOIN PBINV.INV101 ON TCMCD = COMLTD AND TPLNT = XPLANT AND TDVSN = DIV 
--AND TCITN = ITNO AND CLS = '30' GROUP BY TPLNT,TDVSN,TMODL;