SELECT TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO,TMP.ITNM,TMP.XUNIT,
	SUM(TMP.BGQT),SUM(TMP.INQT),SUM(TMP.USQT),SUM(TMP.BGQT + TMP.INQT - TMP.USQT)
FROM ( 
SELECT A.WBPLANT AS PLANT,A.WBDVSN AS DVSN,SUBSTRING(C.PDCD,1,2) AS PDCD,
		A.WBITNO AS ITNO,D.ITNM AS ITNM,C.XUNIT AS XUNIT,
DECIMAL((A.WBBGQT / C.CONVQTY),15,1) AS BGQT,
DECIMAL((A.WBINQT / C.CONVQTY),15,1) AS INQT,
DECIMAL((A.WBUSQT1 + A.WBUSQT2 + A.WBUSQT3 + A.WBUSQT4 + A.WBUSQT5 + A.WBUSQT6
	+ A.WBUSQT7 + A.WBUSQT8 + A.WBUSQTA) / C.CONVQTY,15,1) AS USQT
FROM PBWIP.WIP002 A INNER JOIN PBINV.INV101 C
	ON A.WBCMCD = C.COMLTD AND A.WBPLANT = C.XPLANT AND
		A.WBDVSN = C.DIV AND A.WBITNO = C.ITNO
	INNER JOIN PBINV.INV002 D
	ON C.COMLTD = D.COMLTD AND C.ITNO = D.ITNO
WHERE A.WBCMCD = '01' AND A.WBYEAR = '2010' AND A.WBMONTH = '08' AND A.WBIOCD <> '3'
UNION ALL
SELECT A.WCPLANT AS PLANT,A.WCDVSN AS DVSN,SUBSTRING(C.PDCD,1,2) AS PDCD,
		A.WCITNO AS ITNO,D.ITNM AS ITNM,C.XUNIT AS XUNIT,
(B.BGUQTY + B.BGRQTY + B.BGSQTY) AS BGQT,
DECIMAL((A.WCINQT / C.CONVQTY),15,1) AS INQT,
DECIMAL((A.WCUSQT1 + A.WCUSQT2 + A.WCUSQT3 + A.WCUSQT4 + A.WCUSQT5 + A.WCUSQT6
	+ A.WCUSQT8) / C.CONVQTY,15,1) AS USQT
FROM PBWIP.WIP003 A INNER JOIN PBINV.INV402 B
	ON A.WCCMCD = B.COMLTD AND A.WCPLANT = B.XPLANT AND A.WCDVSN = B.DIV AND
		A.WCITNO = B.ITNO AND A.WCYEAR||A.WCMONTH = B.XYEAR
	INNER JOIN PBINV.INV101 C
	ON B.COMLTD = C.COMLTD AND B.XPLANT = C.XPLANT AND
		B.DIV = C.DIV AND B.ITNO = C.ITNO
	INNER JOIN PBINV.INV002 D
	ON C.COMLTD = D.COMLTD AND C.ITNO = D.ITNO
WHERE A.WCCMCD = '01' AND A.WCYEAR = '2010' AND A.WCMONTH = '08' 
) TMP
WHERE TMP.BGQT <> 0 OR TMP.INQT <> 0 OR TMP.USQT <> 0
GROUP BY TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO,TMP.ITNM,TMP.XUNIT
ORDER BY TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO;


-- 재공수량 버전
SELECT TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO,TMP.ITNM,TMP.XUNIT,
	SUM(TMP.BGQT),SUM(TMP.INQT),SUM(TMP.BGQT + TMP.INQT - TMP.OHQT),SUM(TMP.OHQT)
FROM (
SELECT aaa."WBPLANT" AS PLANT,  
aaa."WBDVSN" AS DVSN,
"PBINV"."INV101"."PDCD" AS PDCD, 
aaa."WBITNO" AS ITNO,   
"PBINV"."INV002"."ITNM" AS ITNM,   
"PBINV"."INV101"."XUNIT" AS XUNIT,  
SUM ( DECIMAL(( CASE aaa."WBYEAR"||aaa."WBMONTH"
		WHEN '201007' THEN aaa."WBBGQT"
		ELSE 0 END ) / "PBINV"."INV101"."CONVQTY",15,1) ) as bgqt,    
SUM ( DECIMAL(( CASE aaa."WBYEAR"||aaa."WBMONTH"
		WHEN '201008' THEN 0
		ELSE aaa."WBINQT" END ) /"PBINV"."INV101"."CONVQTY",15,1) ) as inqt,  
SUM ( DECIMAL(( CASE aaa."WBYEAR"||aaa."WBMONTH"
		WHEN '201008' THEN aaa."WBBGQT"
		ELSE 0 END ) / "PBINV"."INV101"."CONVQTY",15,1)) as ohqt
FROM "PBWIP"."WIP002" aaa,    
         "PBINV"."INV002",   
         "PBINV"."INV101"
WHERE ( aaa."WBCMCD" = "PBINV"."INV002"."COMLTD" ) and  
         ( aaa."WBITNO" = "PBINV"."INV002"."ITNO" ) and  
         ( aaa."WBCMCD" = "PBINV"."INV101"."COMLTD" ) and  
         ( aaa."WBPLANT" = "PBINV"."INV101"."XPLANT" ) and  
         ( aaa."WBDVSN" = "PBINV"."INV101"."DIV" ) and  
         ( aaa."WBITNO" = "PBINV"."INV101"."ITNO" ) and
         ( ( aaa."WBCMCD" = '01' ) AND 
			( aaa."WBYEAR"||aaa."WBMONTH" >= '201007' ) AND 
			( aaa."WBYEAR"||aaa."WBMONTH" <= '201008' ) AND    
			( aaa."WBIOCD" <> '3' ) AND
         NOT ( aaa."WBBGQT"= 0 AND aaa."WBBGAT1" = 0 AND aaa."WBINQT" = 0 AND aaa."WBINAT1" = 0 AND
           aaa."WBINAT2" = 0 AND aaa."WBINAT3" = 0 AND aaa."WBUSQT1" = 0 AND aaa."WBUSAT1" = 0 AND
           aaa."WBUSQT2" = 0 AND aaa."WBUSAT2" = 0 AND aaa."WBUSQT3" = 0 AND aaa."WBUSAT3" = 0 AND
           aaa."WBUSQT4" = 0 AND aaa."WBUSAT4" = 0 AND aaa."WBUSQT5" = 0 AND aaa."WBUSAT5" = 0 AND
           aaa."WBUSQT6" = 0 AND aaa."WBUSAT6" = 0 AND aaa."WBUSQT7" = 0 AND aaa."WBUSAT7" = 0 AND
           aaa."WBUSQT8" = 0 AND aaa."WBUSAT8" = 0 AND aaa."WBUSAT9" = 0 AND aaa."WBUSQTA" = 0 AND
           aaa."WBUSATA" = 0 ))
GROUP BY aaa."WBPLANT",  
         aaa."WBDVSN",
         "PBINV"."INV101"."PDCD",
         aaa."WBITNO",   
         "PBINV"."INV002"."ITNM",   
         "PBINV"."INV101"."XUNIT"

UNION ALL

SELECT aaa."WCPLANT" AS PLANT,
aaa."WCDVSN" AS DVSN,
"PBINV"."INV101"."PDCD" AS PDCD,
aaa."WCITNO" AS ITNO,   
"PBINV"."INV002"."ITNM" AS ITNM,
"PBINV"."INV101"."XUNIT" AS XUNIT,
SUM ( DECIMAL(CASE aaa."WCYEAR"||aaa."WCMONTH"
		WHEN '201007' THEN ("PBINV"."INV402"."BGUQTY" + 
			"PBINV"."INV402"."BGRQTY" + "PBINV"."INV402"."BGSQTY") / "PBINV"."INV101"."CONVQTY"
		ELSE 0 END ,15,1)) as bgqt,    
SUM ( DECIMAL(CASE aaa."WCYEAR"||aaa."WCMONTH"
		WHEN '201008' THEN 0
		ELSE aaa."WCINQT" / "PBINV"."INV101"."CONVQTY" END ,15,1)) as inqt,  
SUM ( DECIMAL(CASE "PBINV"."INV402"."XYEAR"
		WHEN '201007' THEN ("PBINV"."INV402"."OHUQTY" + 
			"PBINV"."INV402"."OHRQTY" + "PBINV"."INV402"."OHSQTY") / "PBINV"."INV101"."CONVQTY"
		ELSE 0 END ,15,1)) as ohqt 
FROM "PBWIP"."WIP003" aaa,
         "PBINV"."INV002",   
         "PBINV"."INV101",   
         "PBINV"."INV402"
   WHERE ( aaa."WCCMCD" = "PBINV"."INV002"."COMLTD" ) and  
         ( aaa."WCITNO" = "PBINV"."INV002"."ITNO" ) and  
         ( aaa."WCCMCD" = "PBINV"."INV101"."COMLTD" ) and  
         ( aaa."WCPLANT" = "PBINV"."INV101"."XPLANT" ) and  
         ( aaa."WCDVSN" = "PBINV"."INV101"."DIV" ) and  
         ( aaa."WCITNO" = "PBINV"."INV101"."ITNO" ) and  
         ( aaa."WCCMCD" = "PBINV"."INV402"."COMLTD" ) and  
         ( aaa."WCPLANT" = "PBINV"."INV402"."XPLANT" ) and  
         ( aaa."WCDVSN" = "PBINV"."INV402"."DIV" ) and  
         ( aaa."WCITNO" = "PBINV"."INV402"."ITNO" ) and
         ( aaa."WCYEAR"||aaa."WCMONTH" = "PBINV"."INV402"."XYEAR" ) AND
         ( aaa."WCCMCD" = '01' and
				aaa."WCYEAR"||aaa."WCMONTH" >= '201007'  AND 
				 aaa."WCYEAR"||aaa."WCMONTH" <= '201008' )AND 
          (aaa."WCBGAT1" <> 0 OR aaa."WCINAT1" <> 0 OR aaa."WCUSAT1" <> 0 OR
           aaa."WCUSAT2" <> 0 OR aaa."WCUSAT3" <> 0 OR aaa."WCUSAT4" <> 0 OR
           aaa."WCUSAT5" <> 0 OR aaa."WCUSAT6" <> 0 OR aaa."WCUSAT7" <> 0 OR
           aaa."WCUSAT8" <> 0 OR aaa."WCUSAT9" <> 0 OR 
           "PBINV"."INV402"."BGUQTY" <> 0 OR "PBINV"."INV402"."BGRQTY" <> 0 OR "PBINV"."INV402"."BGSQTY" <> 0 OR
           "PBINV"."INV402"."OHUQTY" <> 0 OR "PBINV"."INV402"."OHRQTY" <> 0 OR "PBINV"."INV402"."OHSQTY" <> 0 OR
           "PBINV"."INV402"."INTQTY" <> 0 OR "PBINV"."INV402"."OUTQTY" <> 0)
GROUP BY aaa."WCPLANT",
         aaa."WCDVSN",
         "PBINV"."INV101"."PDCD",
         aaa."WCITNO",   
         "PBINV"."INV002"."ITNM",   
         "PBINV"."INV101"."XUNIT") TMP
WHERE TMP.BGQT <> 0 OR TMP.INQT <> 0 OR TMP.OHQT <> 0
GROUP BY TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO,TMP.ITNM,TMP.XUNIT
ORDER BY TMP.PLANT,TMP.DVSN,TMP.PDCD,TMP.ITNO;