SELECT AS_AREACODE       ,   
       AS_DIVISIONCODE   ,   
       B.ITEMCODE       ,   
       C.ITEMNAME       ,   
       B.SUPPLIERCODE   ,
       D.SUPPLIERKORNAME,   
		 AS_PRODUCTGROUP  ,
       AS_MODELGROUP    ,
		 AS_CLASS	,
		 AS_SOURCE	,
		 F.USEFLAG	,
		 F.APPLYFROM	,
       ' '   DEL_CHK       
FROM TMSTPARTCOST B, 
     (SELECT A.AREACODE       AS_AREACODE     ,   
            A.DIVISIONCODE   AS_DIVISIONCODE ,   
            A.ITEMCODE       AS_ITEMCODE     ,
				A.PRODUCTGROUP   AS_PRODUCTGROUP ,
            A.MODELGROUP     AS_MODELGROUP,
				A.ITEMCLASS AS_CLASS,
				A.ITEMBUYSOURCE AS_SOURCE
      FROM TMSTMODEL  A
            WHERE A.AREACODE       = @ps_AreaCode
               AND A.DIVISIONCODE   = @ps_DivisionCode
               AND A.PRODUCTGROUP   LIKE @ps_ProductGroup
               AND A.MODELGROUP     LIKE @ps_ModelGroup
               AND A.ITEMCLASS	IN ('10', '20', '35', '40', '50') ) AS TEMP,
TMSTITEM        C,
TMSTSUPPLIER    D,
TMSTPARTKB      F
WHERE AS_AREACODE *= F.AREACODE 
	 AND AS_DIVISIONCODE *= F.DIVISIONCODE 
	 AND B.ITEMCODE *= F.ITEMCODE
	 AND B.SUPPLIERCODE *= F.SUPPLIERCODE
	 AND B.ITEMCODE      = AS_ITEMCODE
    AND B.ITEMCODE      *= C.ITEMCODE
    AND B.SUPPLIERCODE  *= D.SUPPLIERCODE
    AND AS_AREACODE + AS_DIVISIONCODE + B.ITEMCODE + B.SUPPLIERCODE  NOT IN
    ( SELECT E.AREACODE + E.DIVISIONCODE + E.ITEMCODE + E.SUPPLIERCODE 
		FROM TQQCITEM E );

