SELECT AA.WDPLANT,AA.WDDVSN, AA.WDITNO, AA.WDCHQT, BB.WEREMK FROM PBWIP.WIP004 AA INNER JOIN PBWIP.WIP005 BB
	ON AA.WDCMCD = BB.WECMCD AND AA.WDSLTY = BB.WESLTY AND
		AA.WDSRNO = BB.WESRNO
WHERE AA.WDCMCD = '01' AND AA.WDDATE >= '20040801' AND AA.WDDATE <= '20040831';