SELECT A.SHIPSHEETNO, 	--발행번호
	A.SHIPDATE, 						--출하일자
	B.APPLYFROM, 				--SR납기일
	A.AREACODE,					--지역
	A.DIVISIONCODE, 				--공장
	B.ITEMCODE, 					--품번,
	D.ITEMNAME, 					--품명,
	A.SHIPQTY, 						--출하수량
	B.CHECKSRNO,				--SR번호
	C.CUSTNAME 					--거래처명
FROM TSHIPSHEET A INNER JOIN TSRORDER B
	ON A.SRNO = B.SRNO
	LEFT OUTER JOIN TMSTCUSTOMER C
	ON A.CUSTCODE = C.CUSTCODE
	INNER JOIN TMSTITEM D
 	ON B.ITEMCODE = D.ITEMCODE
WHERE A.SHIPDATE LIKE '2005.06%' AND A.AREACODE = 'D' AND
	A.DIVISIONCODE = 'V' 
ORDER BY A.SHIPSHEETNO, A.SHIPDATE

