--부대작업 업데이트 정보
UPDATE PBRTN.RTN015
SET RENVMC = IFNULL((select sum(rfmctm)
		from pbrtn.rtn016
		WHERE rfcmcd = '01' AND rfplant = REPLANT AND rfdvsn = REDVSN AND
				rfitno = REITNO AND rfline1 = RELINE1 AND rfline2 = RELINE2 AND
				rfopno = REOPNO and RFEDTO = '99991231'),0),
	RENVLB =  IFNULL((select sum(rflbtm)
		from pbrtn.rtn016
		WHERE rfcmcd = '01' AND rfplant = REPLANT AND rfdvsn = REDVSN AND
				rfitno = REITNO AND rfline1 = RELINE1 AND rfline2 = RELINE2 AND
				rfopno = REOPNO and RFEDTO = '99991231'),0)
WHERE REPLANT = 'D' AND REDVSN = 'A' AND REEDTO = '99991231';

UPDATE PBRTN.RTN013
SET RCNVMC = IFNULL((select sum(rdmctm)
		from pbrtn.rtn014
		WHERE rdcmcd = '01' AND rdplant = RCPLANT AND rddvsn = RCDVSN AND
			rditno = RCITNO AND rdline1 = RCLINE1 AND rdline2 = RCLINE2 AND
			rdopno = RCOPNO and rdflag <> 'D'),0),
	RCNVLB =  IFNULL((select sum(rdlbtm)
		from pbrtn.rtn014
		WHERE rdcmcd = '01' AND rdplant = RCPLANT AND rddvsn = RCDVSN AND
			rditno = RCITNO AND rdline1 = RCLINE1 AND rdline2 = RCLINE2 AND
			rdopno = RCOPNO and rdflag <> 'D'),0)
WHERE RCPLANT = 'D' AND RCDVSN = 'A'

-- 부대작업 에러정보
SELECT * FROM PBRTN.RTN016 BB
WHERE BB.RFEDTO = '99991231' AND NOT EXISTS
( SELECT * FROM PBRTN.RTN014 AA
WHERE AA.RDLOGID = BB.RFLOGID );

SELECT * FROM PBRTN.RTN016 BB
WHERE BB.RFPLANT = 'D' AND BB.RFDVSN = 'A' AND BB.RFEDTO = '99991231' AND NOT EXISTS
( SELECT * FROM PBRTN.RTN014 AA
WHERE AA.RDPLANT = 'D' AND AA.RDDVSN = 'A' AND 
	AA.RDLOGID = BB.RFLOGID );

SELECT * FROM PBRTN.RTN014 BB
WHERE BB.RDPLANT = 'D' AND BB.RDDVSN = 'A'  AND NOT EXISTS
( SELECT * FROM PBRTN.RTN016 AA
WHERE AA.RFPLANT = 'D' AND AA.RFDVSN = 'A' AND AA.RFEDTO = '99991231' AND
	AA.RFLOGID = BB.RDLOGID );

-- 부대작업 에러처리
--INSERT INTO PBRTN.RTN016  
( RFLOGID, RFCMCD, RFPLANT, RFDVSN, RFITNO, RFLINE1, RFLINE2, RFOPNO, RFNVMO, RFMCNO, 
RFTERM, RFMCTM, RFLBTM, RFREMK, RFFLAG, RFEPNO, RFEDFM,  
RFEDTO, RFIPAD, RFUPDT, RFSYDT )
SELECT DISTINCT BB.RDLOGID, BB.RDCMCD, BB.RDPLANT, BB.RDDVSN, BB.RDITNO, BB.RDLINE1, BB.RDLINE2, 
BB.RDOPNO, BB.RDNVMO, BB.RDMCNO, BB.RDTERM, BB.RDMCTM, BB.RDLBTM, BB.RDREMK, BB.RDFLAG, 
'000030', CC.RCEDFM,   
'99991231', '', '20120406', 'INS01'
FROM PBRTN.RTN014 BB INNER JOIN PBRTN.RTN013 CC 
  ON CC.RCCMCD = BB.RDCMCD AND
	CC.RCPLANT = BB.RDPLANT AND CC.RCDVSN = BB.RDDVSN AND
	CC.RCITNO = BB.RDITNO AND CC.RCLINE1 = BB.RDLINE1 AND
	CC.RCLINE2 = BB.RDLINE2 AND CC.RCOPNO = BB.RDOPNO
WHERE BB.RDPLANT = 'D' AND BB.RDDVSN = 'V' AND CC.RCDLCHK = 'Y' AND NOT EXISTS
( SELECT * FROM PBRTN.RTN016 AA
WHERE AA.RFPLANT = 'D' AND AA.RFDVSN = 'V' AND AA.RFEDTO = '99991231' AND
	AA.RFLOGID = BB.RDLOGID );

-- 검증 SQL
SELECT * FROM PBRTN.RTN016 BB
WHERE BB.RFPLANT = 'D' AND BB.RFDVSN = 'H' AND BB.RFEDTO = '99991231' AND NOT EXISTS
( SELECT * FROM PBRTN.RTN014 AA
WHERE AA.RDPLANT = 'D' AND AA.RDDVSN = 'H' AND 
	AA.RDLOGID = BB.RFLOGID );

SELECT * FROM PBRTN.RTN014 BB
WHERE BB.RDPLANT = 'D' AND BB.RDDVSN = 'A'  AND NOT EXISTS
( SELECT * FROM PBRTN.RTN016 AA
WHERE AA.RFPLANT = 'D' AND AA.RFDVSN = 'A' AND AA.RFEDTO = '99991231' AND
	AA.RFLOGID = BB.RDLOGID );

SELECT * FROM PBRTN.RTN015
WHERE REPLANT = 'D' AND REDVSN = 'M' AND REITNO = '95959759';

SELECT * FROM PBRTN.RTN016
WHERE RFITNO = '622578' AND RFOPNO = '50' AND RFEDTO = '99991231';

SELECT * FROM PBRTN.RTN014
WHERE RDITNO = '622578' AND RDOPNO = '50' ;

SELECT * FROM PBRTN.RTN015
WHERE RDPLANT = 'D' AND RDDVSN = 'A' AND RDITNO  = '211301' AND RDOPNO = '10';


-- 유사품번, 대표품번 데이타 오류 확인
//SELECT * FROM PBINV.INV401
//WHERE COMLTD = '01' AND XPLANT = 'D' AND DIV = 'A' AND INPTDT > '2012-01-18 13:00:00'; 

//SELECT * FROM PBRTN.RTN013
//WHERE RCCMCD = '01' AND RCPLANT = 'D' AND RCDVSN = 'H' AND RCITNO IN ('616040','616990');

//SELECT * FROM PBRTN.RTN011
//WHERE RACMCD = '01' AND RAPLANT = 'D' AND RADVSN = 'H' AND RAITNO = '613254';

SELECT * FROM PBRTN.RTN011 A
WHERE A.RACMCD = '01' AND A.RAPLANT = 'D' AND A.RADVSN = 'H' AND 
A.RAITNO1 IN ( SELECT B.RCITNO FROM PBRTN.RTN013 B WHERE B.RCCMCD = '01' AND B.RCPLANT = 'D' AND B.RCDVSN = 'H' );

SELECT * FROM PBRTN.RTN018 A
WHERE A.RHCMCD = '01' AND A.RHPLANT = 'D' AND A.RHDVSN = 'H' AND A.RHEDTO  = '99991231' AND
A.RHITNO1 IN ( SELECT B.RCITNO FROM PBRTN.RTN013 B WHERE B.RCCMCD = '01' AND B.RCPLANT = 'D' AND B.RCDVSN = 'H' );