USE [ORMS]
GO

/****** Object:  Table [dbo].[TH_DATA_DAY]    Script Date: 01/17/2011 10:07:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TH_DATA_DAY](
	[PROD_YMD] [varchar](8) NOT NULL DEFAULT '',
	[PROD_SHIFT] [varchar](1) NOT NULL DEFAULT '',
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
 CONSTRAINT [PK_TH_DATA_DAY] PRIMARY KEY CLUSTERED 
(
	[PROD_YMD], [PROD_SHIFT]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

