USE [ORMS]
GO

/****** Object:  Table [dbo].[TH_DATA_TIME]    Script Date: 01/17/2011 10:07:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TH_DATA_TIME](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[PROD_YMD] [varchar](8) NULL,
	[MODEL] [varchar](10) NULL,
	[TIME_ZONE] [varchar](11) NULL,
	[WORK_QTY] [int] NULL,
	[WORK_RATE] [float] NULL,
	[PROD_SHIFT] [varchar](1) NULL,
	[SEQ] [int] NULL,
 CONSTRAINT [PK_TH_DATA_TIME] PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

