USE [ORMS]
GO

/****** Object:  Table [dbo].[TH_ERROR]    Script Date: 01/17/2011 10:07:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TH_ERROR](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[ERR_MSG] [varchar](100) NULL,
	[ERR_DATE] [datetime] NULL,
 CONSTRAINT [PK_TH_ERROR] PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

