USE [ORMS]
GO

/****** Object:  Table [dbo].[TH_INF_DATA]    Script Date: 01/17/2011 10:07:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TH_INF_DATA](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[INF_TIME] [datetime] NULL,
	[MODEL] [varchar](10) NULL,
	[PROD_QTY] [int] NULL,
	[PROD_YMD] [varchar](8) NULL,
	[PROD_SHIFT] [varchar](1) NULL,
	[PROD_HH] [varchar](3) NULL,
	[CYCLE_TIME] [int] NULL,
	[FLAG] [varchar](1) NULL,
 CONSTRAINT [PK_TH_INF_DATA] PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

