USE [ORMS]
GO

/****** Object:  Table [dbo].[TH_WORK_TIME]    Script Date: 01/17/2011 10:08:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TH_WORK_TIME](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[HH] [varchar](3) NULL,
	[WORK_TIME] [int] NULL,
 CONSTRAINT [PK_TH_WORK_TIME] PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

