USE [ORMS]
GO

/****** Object:  Table [dbo].[TM_CODE]    Script Date: 01/17/2011 10:08:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TM_CODE](
	[MCD] [varchar](10) NOT NULL,
	[SCD] [varchar](10) NOT NULL,
	[CDNAME] [varchar](60) NULL,
	[REMARK] [varchar](40) NULL,
	[ETC01] [varchar](10) NULL,
	[ETC02] [varchar](10) NULL,
	[ETC03] [varchar](10) NULL,
	[ETC04] [varchar](10) NULL,
 CONSTRAINT [PK_TM_CODE] PRIMARY KEY CLUSTERED 
(
	[MCD] ASC,
	[SCD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

